#!/usr/bin/env bash
# ==============================================================================
#  reality-sni-check.sh  —  Reality dest/SNI 候选测速与合规检测
#
#  在【落地服务器】上跑：为该机测出握手最快、且满足 Reality 要求
#  (TLS1.3 + h2 + X25519) 的 SNI 候选，供 VLESS-Reality dest 选用。
#
#  用法:
#    ./reality-sni-check.sh                 # 无参数 → 进交互菜单(选测试项)
#    ./reality-sni-check.sh -l              # 列出所有分类
#    ./reality-sni-check.sh -c edu          # 直接只测"大学"分类(跳过菜单)
#    ./reality-sni-check.sh -c edu,tech     # 测多个分类(逗号/空格分隔)
#    ./reality-sni-check.sh -r jp           # 按地区推荐(该区归属站+全球站)
#    ./reality-sni-check.sh -a "a.com b.com"# 追加自定义站点一起测
#    ./reality-sni-check.sh -i              # 只进交互输入模式(一行可多站)
#    ./reality-sni-check.sh -n 5 -t 6       # 每站探测5次、单次超时6s
#    SNI_HOSTS="a.com b.com" ./reality-sni-check.sh   # 用自己的清单替换全部
#
#  分类键: cdn(全球CDN) cloud(云/开发) tech(科技大厂) fin(金融) edu(大学)
#          media(流媒体) social(社交) gaming(游戏) ecom(电商) region(区域锚点)
#  地区键: global us eu jp hk sg cn au kr   (-r 用)
#  依赖: bash curl openssl timeout  (常见发行版默认都有)
# ------------------------------------------------------------------------------
#  免责声明 (DISCLAIMER):
#    本脚本仅是一个网络连通性与 TLS 握手参数的检测工具，功能等同于
#    curl / openssl 的批量封装，用于测量本机到公开网站的握手延迟、
#    TLS 版本、ALPN 与证书链等公开可见信息，供技术研究、服务器选型、
#    网络诊断与合法合规用途参考。
#
#    - 脚本本身不建立任何代理、不修改系统、不发送数据到第三方，
#      所有请求均为对目标站点 443 端口的标准 HTTPS 探测。
#    - 检测结果仅反映测量当时的网络状况，不构成任何保证或建议。
#    - 使用者须自行确保其使用方式符合所在地及目标服务器所在地的
#      法律法规及相关服务条款。因使用本脚本产生的任何后果，
#      由使用者自行承担，作者与分发者不承担任何责任。
#    - 请勿将本工具用于任何未经授权、违法或侵犯他人权益的用途。
#
#    继续使用即表示您已阅读、理解并同意上述条款。
# ==============================================================================
set -u

# ================== 内置候选站点：按分类组织 ==================
# 脚本会自动测每站在【本机】的握手延迟+合规+证书链，不合适的自动标记，不用手删。
# 分类键: cdn cloud tech fin edu media social gaming ecom region  (用 -c 选，见 -h)

GRP_cdn=(                      # 全球 CDN / anycast，任何区就近命中，最干净
  www.cloudflare.com
  www.apple.com
  www.icloud.com
  gateway.icloud.com
  swscan.apple.com            # Apple 软更源，链短握手干净，经典 dest
  www.amazon.com
  www.microsoft.com           # 常因证书链长不合规，留着看它被筛掉
  addons.mozilla.org          # 社区长期验证的干净 dest
  www.python.org
  www.fastly.com
)
GRP_cloud=(                   # 云/开发基础设施，TLS 一般极规范
  aws.amazon.com
  azure.microsoft.com
  www.digitalocean.com
  gitlab.com
  registry.npmjs.org
  www.jsdelivr.com
  www.vercel.com
  www.netlify.com
  www.oracle.com
  www.ibm.com
)
GRP_tech=(                    # 科技/半导体/硬件大厂
  www.amd.com
  www.intel.com
  www.nvidia.com
  www.qualcomm.com
  www.arm.com
  www.tesla.com
  www.samsung.com
  www.sony.com
  www.lg.com
  www.dell.com
  www.hp.com
  www.lenovo.com
  www.cisco.com
  www.adobe.com
)
GRP_fin=(                     # 金融/支付/银行，证书规矩全球可达
  www.paypal.com
  www.visa.com
  www.mastercard.com
  www.americanexpress.com
  www.stripe.com
  www.jpmorgan.com
  www.goldmansachs.com
  www.hsbc.com
  www.citi.com
  www.blackrock.com
)
GRP_edu=(                     # 大学/教育机构，冷门不被封，选 CDN 托管的名校主站
  www.mit.edu
  www.stanford.edu
  www.harvard.edu
  www.berkeley.edu
  www.cornell.edu
  www.princeton.edu
  www.yale.edu
  www.columbia.edu
  www.ox.ac.uk
  www.cam.ac.uk
  www.imperial.ac.uk
  www.ethz.ch
  www.epfl.ch
  www.u-tokyo.ac.jp
  www.kyoto-u.ac.jp
  www.nus.edu.sg
  www.ntu.edu.sg
  www.hku.hk
  www.hkust.edu.hk
  www.tsinghua.edu.cn
  www.pku.edu.cn
  www.unimelb.edu.au
  www.utoronto.ca
)
GRP_media=(                   # 流媒体/内容平台
  www.imdb.com
)
GRP_social=(                  # 社交平台 (dest 从落地机方向可达即可)
  www.wordpress.com
  www.snapchat.com
)
GRP_gaming=(                  # 游戏平台/发行商
  www.epicgames.com
  www.riotgames.com
  www.ea.com
  www.ubisoft.com
  www.playstation.com
  www.nintendo.com
  www.xbox.com
  www.blizzard.com
)
GRP_ecom=(                    # 电商/零售/品牌
  www.ebay.com
  www.walmart.com
  www.target.com
  www.bestbuy.com
  www.shopify.com
  www.alibaba.com
  www.ikea.com
  www.nike.com
  www.adidas.com
  www.zara.com
)
GRP_region=(                  # 区域锚点 (按落地机大区就近选，最自然)
  www.lovelive-anime.jp       # 日本
  www.yahoo.co.jp
  www.ana.co.jp
  www.mercedes-benz.com       # 欧洲
  www.bmw.com
  www.audi.com
  www.lufthansa.com
  www.singaporeair.com        # 东南亚
  www.cathaypacific.com       # 香港
  www.qantas.com              # 澳洲
  www.salesforce.com          # 北美
)

# 分类顺序与中文标签 (键:标签)
CAT_KEYS=(cdn cloud tech fin edu media social gaming ecom region)
cat_label() {
  case "$1" in
    cdn)    echo "全球 CDN/anycast" ;;
    cloud)  echo "云/开发基础设施" ;;
    tech)   echo "科技/半导体大厂" ;;
    fin)    echo "金融/支付/银行" ;;
    edu)    echo "大学/教育机构" ;;
    media)  echo "流媒体/内容" ;;
    social) echo "社交平台" ;;
    gaming) echo "游戏平台" ;;
    ecom)   echo "电商/零售/品牌" ;;
    region) echo "区域锚点(日/欧/东南亚/港/澳)" ;;
    *)      echo "$1" ;;
  esac
}
# 取某分类的站点 (可移植写法，不依赖 nameref)
cat_hosts() {
  case "$1" in
    cdn)    printf '%s\n' "${GRP_cdn[@]}" ;;
    cloud)  printf '%s\n' "${GRP_cloud[@]}" ;;
    tech)   printf '%s\n' "${GRP_tech[@]}" ;;
    fin)    printf '%s\n' "${GRP_fin[@]}" ;;
    edu)    printf '%s\n' "${GRP_edu[@]}" ;;
    media)  printf '%s\n' "${GRP_media[@]}" ;;
    social) printf '%s\n' "${GRP_social[@]}" ;;
    gaming) printf '%s\n' "${GRP_gaming[@]}" ;;
    ecom)   printf '%s\n' "${GRP_ecom[@]}" ;;
    region) printf '%s\n' "${GRP_region[@]}" ;;
    *) : ;;
  esac
}

# ---------------- 地区标签 ----------------
# SNI 站点的“归属地区”：落地机在某区时，选该区归属站更贴合正常流量画像。
# 未列出的一律 global（大厂 CDN，任何区都自然）。
host_region() {
  case "$1" in
    www.lovelive-anime.jp|www.yahoo.co.jp|www.ana.co.jp|www.u-tokyo.ac.jp|www.kyoto-u.ac.jp) echo jp ;;
    www.mercedes-benz.com|www.bmw.com|www.audi.com|www.lufthansa.com|www.ox.ac.uk|www.cam.ac.uk|www.imperial.ac.uk|www.ethz.ch|www.epfl.ch|www.zara.com|www.ikea.com|www.adidas.com) echo eu ;;
    www.nus.edu.sg|www.ntu.edu.sg|www.singaporeair.com) echo sg ;;
    www.hku.hk|www.hkust.edu.hk|www.cathaypacific.com) echo hk ;;
    www.tsinghua.edu.cn|www.pku.edu.cn|www.alibaba.com) echo cn ;;
    www.qantas.com|www.unimelb.edu.au) echo au ;;
    www.mit.edu|www.stanford.edu|www.harvard.edu|www.berkeley.edu|www.cornell.edu|www.princeton.edu|www.yale.edu|www.columbia.edu|www.utoronto.ca) echo us ;;
    *) echo global ;;
  esac
}

# ---------------- SNI 风险后缀 ----------------
# 内置 GFWList 整域名/后缀规则。SNI 层只能看到域名，所以不内置 URL 路径/正则规则，避免误伤。
# 来源: https://github.com/gfwlist/gfwlist ，更新时重新生成下面的 GFWLIST_SUFFIXES。
GFWLIST_SUFFIXES=(
  "000webhost.com"
  "1-apple.com.tw"
  "1000giri.net"
  "10beasts.net"
  "10musume.com"
  "12bet.com"
  "12vpn.com"
  "12vpn.net"
  "1337x.to"
  "141jj.com"
  "1688.com.au"
  "173ng.com"
  "18board.com"
  "18comic.org"
  "18mh.net"
  "1984bbs.com"
  "1991way.com"
  "1e100.net"
  "1lib.sk"
  "1point3acres.com"
  "1pondo.tv"
  "2008xianzhang.info"
  "2021hkcharter.com"
  "2047.name"
  "2047.one"
  "2049bbs.xyz"
  "233abc.com"
  "24hbook.com"
  "24hrs.ca"
  "32red.com"
  "36rain.com"
  "404museum.com"
  "466453.com"
  "4bluestones.biz"
  "4everproxy.com"
  "4rbtv.com"
  "4shared.com"
  "500px.com"
  "500px.org"
  "51.ca"
  "51jav.org"
  "51luoben.com"
  "5278.cc"
  "611study.com"
  "611study.icu"
  "63i.com"
  "666pool.cn"
  "69shuba.cx"
  "6do.news"
  "6do.world"
  "6park.com"
  "6parkbbs.com"
  "6parker.com"
  "6parknews.com"
  "7capture.com"
  "881903.com"
  "89-64.org"
  "8964museum.com"
  "8z1.net"
  "91dasai.com"
  "91porn.com"
  "91porny.com"
  "91vps.club"
  "996.icu"
  "99btgc01.com"
  "9bis.com"
  "9bis.net"
  "9cache.com"
  "9gag.com"
  "9news.com.au"
  "9oju31.launches.appsflyersdk.com"
  "a-normal-day.com"
  "a248.e.akamai.net"
  "aave.com"
  "abc.net.au"
  "abc.xyz"
  "abebooks.co.uk"
  "abebooks.com"
  "abematv.akamaized.net"
  "aboluowang.com"
  "about.gitlab.com"
  "about.me"
  "abplive.com"
  "acast.com"
  "accountboy.com"
  "accountkit.com"
  "acevpn.com"
  "acg.mn"
  "acg.rip"
  "acgbox.org"
  "acgkj.com"
  "acgnx.se"
  "activpn.com"
  "aculo.us"
  "adcex.com"
  "addictedtocoffee.de"
  "addyoutube.com"
  "adguard-vpn.com"
  "admin.recaptcha.net"
  "admob.com"
  "ads-twitter.com"
  "adsense.com"
  "adult-sex-games.com"
  "advanscene.com"
  "advertfan.com"
  "advertisercommunity.com"
  "aei.org"
  "aenhancers.com"
  "aex.com"
  "af.mil"
  "afr.com"
  "afreecatv.com"
  "agnesb.fr"
  "agoogleaday.com"
  "agro.hk"
  "ai.dev"
  "ai.studio"
  "aiosearch.com"
  "aiph.net"
  "airconsole.com"
  "airitilibrary.com"
  "airuniversity.af.edu"
  "airvpn.org"
  "ait.org.tw"
  "aiweiweiblog.com"
  "akamai.tvb.com"
  "akiba-online.com"
  "akiba-web.com"
  "akile.io"
  "akinator.com"
  "akow.org"
  "alabout.com"
  "alasbarricadas.org"
  "alforattv.net"
  "alive.bar"
  "aljazeera.com"
  "aljazeera.net"
  "alkasir.com"
  "all4mom.org"
  "allcoin.com"
  "allconnected.co"
  "alldrawnsex.com"
  "allfinegirls.com"
  "allinfa.com"
  "allmovie.com"
  "alternate-tools.com"
  "altrec.com"
  "alwaysdata.com"
  "alwaysdata.net"
  "alwaysvpn.com"
  "am730.com.hk"
  "amazon.co.jp"
  "amazonvideo.com"
  "ameblo.jp"
  "americangreencard.com"
  "americorps.gov"
  "amiblockedornot.com"
  "amnesty.org"
  "amnesty.org.hk"
  "amnestyusa.org"
  "ampproject.org"
  "amuletmc.com"
  "anchor.fm"
  "anchorfree.com"
  "ancsconf.org"
  "andfaraway.net"
  "android-x86.org"
  "android.com"
  "androidapksfree.com"
  "androidify.com"
  "androidtv.com"
  "angela-merkel.de"
  "angola.org"
  "angularjs.org"
  "aniscartujo.com"
  "annas-archive.gd"
  "annas-archive.gl"
  "annas-archive.pk"
  "anobii.com"
  "anonfiles.com"
  "anonymouse.org"
  "anthonycalzadilla.com"
  "anthropic.com"
  "antpool.com"
  "anuneko.com"
  "ao3.org"
  "aobo.com.au"
  "aomedia.org"
  "aomiwang.com"
  "aoxvpn.com"
  "apartmentratings.com"
  "apartments.com"
  "apat1989.org"
  "api-gl.lbkrs.com"
  "api-secure.recaptcha.net"
  "api-verify.recaptcha.net"
  "api.ai"
  "api.futunn.com"
  "api.lbkrs.com"
  "api.moomoobull.com"
  "api.palworldgame.com"
  "api.pureapk.com"
  "api.recaptcha.net"
  "api.steampowered.com"
  "api5.futunn.com"
  "apiary.io"
  "apigee.com"
  "apk.support"
  "apkcombo.com"
  "apkmirror.com"
  "apkmonk.com"
  "apkplz.com"
  "apkpure.com"
  "apkpure.net"
  "app.box.com"
  "app.cloudcone.com"
  "app.element.io"
  "app.smartmailcloud.com"
  "appadvice.com"
  "appbrain.com"
  "appledaily.com"
  "appledaily.com.tw"
  "apps.evozi.com"
  "appsocks.net"
  "appspot.com"
  "appsto.re"
  "aptoide.com"
  "archive-it.org"
  "archive.fo"
  "archive.is"
  "archive.li"
  "archive.md"
  "archive.org"
  "archive.ph"
  "archive.today"
  "archive.vn"
  "archiveofourown.com"
  "archiveofourown.org"
  "archives.gov"
  "arctosia.com"
  "areca-backup.org"
  "arena.ai"
  "arena.taipei"
  "arethusa.su"
  "arlingtoncemetery.mil"
  "arte.tv"
  "artstation.com"
  "arvanstorage.ir"
  "arweave.org"
  "as.mr"
  "asacp.org"
  "asiaharvest.org"
  "asianage.com"
  "asianews.it"
  "asianfanfics.com"
  "asiansexdiary.com"
  "asiaone.com"
  "asiasociety.org"
  "ask.com"
  "askstudent.com"
  "askynz.net"
  "aspi.org.au"
  "aspistrategist.org.au"
  "assembla.com"
  "assets.bwbx.io"
  "assets.nxtrace.org"
  "assimp.org"
  "astrill.com"
  "atc.org.au"
  "athenaeizou.com"
  "atlanta168.com"
  "atnext.com"
  "auctions.yahoo.co.jp"
  "audacy.com"
  "auntology.fandom.com"
  "autodraw.com"
  "av.movie"
  "av01.tv"
  "avaaz.org"
  "avdb.in"
  "avdb.tv"
  "avg.com"
  "avgle.com"
  "avidemux.org"
  "avistaz.to"
  "avmo.pw"
  "avmoo.pw"
  "avoision.com"
  "axios.com"
  "axureformac.com"
  "azirevpn.com"
  "b-ok.cc"
  "b.hatena.ne.jp"
  "babylonbee.com"
  "backchina.com"
  "backend-v2.crixet.com"
  "bad.news"
  "badiucao.com"
  "baidu.jp"
  "baijie.org"
  "bailandaily.com"
  "baixing.me"
  "baizhi.org"
  "banana-vpn.com"
  "band.us"
  "bandcamp.com"
  "bandwagonhost.com"
  "bangdream.space"
  "bangkokpost.com"
  "bangumi.moe"
  "bangumi.tv"
  "bangyoulater.com"
  "bankmobilevibe.com"
  "bannedbook.org"
  "banorte.com"
  "barnabu.co.uk"
  "barton.de"
  "bastillepost.com"
  "bayvoice.net"
  "bb-chat.tv"
  "bbc.co.uk"
  "bbc.com"
  "bbc.pdn.tritondigital.com"
  "bbcchinese.com"
  "bbchat.tv"
  "bbci.co.uk"
  "bbs.junglobal.net"
  "bbs.mikocon.com"
  "bbs.mychat.to"
  "bbs.naixi.net"
  "bbs.nyinfor.com"
  "bcex.ca"
  "bearteach.com"
  "bebo.com"
  "beeg.com"
  "beepool.com"
  "beepool.org"
  "beevpn.com"
  "behance.net"
  "beijing1989.com"
  "beijing2022.art"
  "beijingspring.com"
  "bellingcat.com"
  "berlinerbericht.de"
  "berlintwitterwall.com"
  "bestvpn.com"
  "bestvpnanalysis.com"
  "bestvpnforchina.net"
  "bestvpnserver.com"
  "bestvpnservice.com"
  "bestvpnusa.com"
  "bet365.com"
  "betaclouds.net"
  "bettergpt.chat"
  "betterhash.net"
  "betternet.co"
  "bettervpn.com"
  "bettween.com"
  "betvictor.com"
  "bfnn.org"
  "bfsh.hk"
  "bgm.tv"
  "bgme.me"
  "bgvpn.com"
  "biblesforamerica.org"
  "bibox.com"
  "biedian.me"
  "big.one"
  "bigjapanesesex.com"
  "bignews.org"
  "bigone.com"
  "bild.de"
  "bilinovel.com"
  "binance.com"
  "binance.org"
  "binancezh.cc"
  "bird.so"
  "bit-z.com"
  "bitbaby.com"
  "bitbay.net"
  "bitchute.com"
  "bitcointalk.org"
  "bitcoinworld.com"
  "bitfinex.com"
  "bitget.com"
  "bithumb.com"
  "bitmex.com"
  "bitshare.com"
  "bitterwinter.org"
  "bittorrent.com"
  "bitvise.com"
  "bitz.ai"
  "bjzc.org"
  "bl-doujinsouko.com"
  "blacked.com"
  "blackmagicdesign.com"
  "blackvpn.com"
  "bleepingcomputer.com"
  "blinkx.com"
  "blip.tv"
  "blockcast.it"
  "blockcn.com"
  "blockedbyhk.com"
  "blockless.com"
  "blocktempo.com"
  "blog.cryptographyengineering.com"
  "blog.de"
  "blog.expofutures.com"
  "blog.fizzik.com"
  "blog.fuckgfw233.org"
  "blog.jackjia.com"
  "blog.martinoei.com"
  "blog.pathtosharepoint.com"
  "blog.pentalogic.net"
  "blog.reimu.net"
  "blog.tiney.com"
  "blogblog.com"
  "blogcatalog.com"
  "blogcity.me"
  "blogger.com"
  "blogjav.net"
  "bloglines.com"
  "bloglovin.com"
  "bloodshed.net"
  "bloomberg.cn"
  "bloomberg.com"
  "bloomberg.de"
  "bloombergview.com"
  "bloomfortune.com"
  "blubrry.com"
  "bmdru.com"
  "bnbstatic.com"
  "bnext.com.tw"
  "bnn.co"
  "bnrmetal.com"
  "boardreader.com"
  "bod.asia"
  "bolehvpn.net"
  "boobstagram.com"
  "book.com.tw"
  "bookdepository.com"
  "books.com.tw"
  "booktopia.com.au"
  "bookwalker.com.tw"
  "boomplay.com"
  "bootstrapcdn.com"
  "borgenmagazine.com"
  "botanwang.com"
  "bowenpress.com"
  "boxpn.com"
  "boxun.com"
  "boxun.tv"
  "boysmaster.com"
  "br.st"
  "braumeister.org"
  "brave.com"
  "bravotube.net"
  "brazzers.com"
  "breached.to"
  "break.com"
  "breakgfw.com"
  "breakingtweets.com"
  "breakwall.net"
  "brill.com"
  "brizzly.com"
  "broadpressinc.com"
  "brookings.edu"
  "brutaltgp.com"
  "bsky.app"
  "bsky.network"
  "bsky.social"
  "bt4g.org"
  "bt4gprx.com"
  "bt95.com"
  "btbit.net"
  "btbtt.co"
  "btbtt.me"
  "btc.com"
  "btc98.com"
  "btcbank.bank"
  "btctrade.im"
  "btdig.com"
  "btguard.com"
  "btku.me"
  "btku.org"
  "budaedu.org"
  "buffered.com"
  "bullguard.com"
  "bullog.org"
  "bullogger.com"
  "bumingbai.net"
  "bunbunhk.com"
  "business-humanrights.org"
  "business.page"
  "businessinsider.com"
  "businesstoday.com.tw"
  "buzzorange.com"
  "buzzsprout.com"
  "bvpn.com"
  "bwgyhw.com"
  "bwh1.net"
  "bx.in.th"
  "bybit.com"
  "bynet.co.il"
  "bypasscensorship.org"
  "byrut.org"
  "c-est-simple.com"
  "c-span.org"
  "c-spanvideo.org"
  "c.mi.com"
  "c2cx.com"
  "c3pool.com"
  "cableav.tv"
  "cablegatesearch.net"
  "cachefly.com"
  "cachefly.net"
  "cactusvpn.com"
  "calebelston.com"
  "calendarz.com"
  "camfrog.com"
  "campaign-archive.com"
  "campaignforuyghurs.org"
  "cams.com"
  "canva.com"
  "canyu.org"
  "caobian.info"
  "caochangqing.com"
  "caoporn.us"
  "cap.org.hk"
  "carfax.com"
  "cari.com.my"
  "caribbeancom.com"
  "carousell.com.hk"
  "carrd.co"
  "cartoonmovement.com"
  "casino.williamhill.com"
  "casinobellini.com"
  "castbox.fm"
  "catbox.moe"
  "catch22.net"
  "catholic.org.hk"
  "catholic.org.tw"
  "cato.org"
  "cattt.com"
  "caus.com"
  "cbc.ca"
  "cbs.ntu.edu.tw"
  "cccat.cc"
  "cccat.co"
  "ccfd.org.tw"
  "cchere.com"
  "cchostvps.xyz"
  "cclife.org"
  "cclifefl.org"
  "ccthere.com"
  "ccthere.net"
  "cdbook.org"
  "cdef.org"
  "cdig.info"
  "cdjp.org"
  "cdn-images.mailchimp.com"
  "cdn-telegram.org"
  "cdn.arstechnica.net"
  "cdn.futustatic.com"
  "cdn.jwplayer.com"
  "cdn.printfriendly.com"
  "cdn.seatguru.com"
  "cdn.softlayer.net"
  "cdn.statically.io"
  "cdninstagram.com"
  "cdp1998.org"
  "cdp2006.org"
  "cdpeu.org"
  "cdpuk.co.uk"
  "cdpweb.org"
  "cdpwu.org"
  "cdw.com"
  "cecc.gov"
  "cellulo.info"
  "cenews.eu"
  "centauro.com.br"
  "centerforhumanreprod.com"
  "centralnation.com"
  "certificate-transparency.org"
  "cfr.org"
  "cg.play-analytics.com"
  "change.org"
  "changp.com"
  "channelnewsasia.com"
  "chanworld.org"
  "chaoex.com"
  "chaos.social"
  "character.ai"
  "chat.com"
  "chat.lmsys.org"
  "chatgpt.com"
  "chatpdf.com"
  "chaturbate.com"
  "checkgfw.com"
  "chengmingmag.com"
  "chenguangcheng.com"
  "chenpokong.com"
  "chenpokongvip.com"
  "chenshan20042005.wordpress.com"
  "cherrysave.com"
  "chhongbi.org"
  "chii.in"
  "china-mmm.net"
  "china-week.com"
  "china101.com"
  "china18.org"
  "china21.com"
  "china21.org"
  "china5000.us"
  "chinaaffairs.org"
  "chinaaid.net"
  "chinaaid.org"
  "chinaaid.us"
  "chinachange.org"
  "chinachannel.hk"
  "chinademocrats.org"
  "chinadialogue.net"
  "chinadigitaltimes.net"
  "chinaelections.org"
  "chinafile.com"
  "chinafreepress.org"
  "chinagfw.org"
  "chinahorizon.org"
  "chinamule.com"
  "chinapress.com.my"
  "chinasocialdemocraticparty.com"
  "chinasoul.org"
  "chinatopsex.com"
  "chinauncensored.tv"
  "chinaview.wordpress.com"
  "chinaworker.info"
  "chinese-memorial.org"
  "chinese.engadget.com"
  "chinesedailynews.com"
  "chinesedemocracy.com"
  "chinesegay.org"
  "chinesen.de"
  "chinesenews.net.au"
  "chineseradioseattle.com"
  "chineseupress.com"
  "chingcheong.com"
  "chobit.cc"
  "chonglangtv.org"
  "christianfreedom.org"
  "christianstudy.com"
  "christiantimes.org.hk"
  "chrlawyers.hk"
  "chrome.com"
  "chromecast.com"
  "chromeexperiments.com"
  "chromestatus.com"
  "ci-en.jp"
  "cia.gov"
  "cici.com"
  "ciciai.com"
  "cirosantilli.com"
  "citizencn.com"
  "citizenlab.ca"
  "citizenlab.org"
  "citypopulation.de"
  "civicparty.hk"
  "civilhrfront.org"
  "civilmedia.tw"
  "civitai.com"
  "cixiaoya.club"
  "ck101.com"
  "classicalguitarblog.net"
  "claude.ai"
  "claude.com"
  "cldr.unicode.org"
  "clearsurance.com"
  "clementine-player.org"
  "clinica-tibet.ru"
  "clipconverter.cc"
  "cloud.dify.ai"
  "cloud.mail.ru"
  "cloudflare-dns.com"
  "cloudflare-ipfs.com"
  "cloudflarestatus.com"
  "cloudfunctions.net"
  "club1069.com"
  "clubhouseapi.com"
  "clyp.it"
  "cmcn.org"
  "cmegroup.com"
  "cmi.org.tw"
  "cms.gov"
  "cmule.com"
  "cmx.im"
  "cn.sandscotaicentral.com"
  "cn.theaustralian.com.au"
  "cn.uptodown.com"
  "cna.com.tw"
  "cnbbnews.wordpress.com"
  "cnbeta.com.tw"
  "cnd.org"
  "cnnews.chosun.com"
  "cnpolitics.org"
  "co.ng.mil"
  "coat.co.jp"
  "cobinhood.com"
  "cochina.org"
  "codeshare.io"
  "codeskulptor.org"
  "cofacts.tw"
  "coffeemanga.to"
  "coinbase.com"
  "coinbene.com"
  "coinex.com"
  "coingecko.com"
  "coingi.com"
  "coinmarketcap.com"
  "coinrail.co.kr"
  "cointiger.com"
  "cointobe.com"
  "coinut.com"
  "colacloud.net"
  "collateralmurder.com"
  "collateralmurder.org"
  "comefromchina.com"
  "comments.app"
  "commentshk.com"
  "communistcrimes.org"
  "communitychoicecu.com"
  "comparitech.com"
  "compileheart.com"
  "connect.facebook.net"
  "conoha.jp"
  "contests.twilio.com"
  "cool18.com"
  "coolaler.com"
  "coolder.com"
  "coolloud.org.tw"
  "coolstuffinc.com"
  "copilot.microsoft.com"
  "costco.com"
  "cotweet.com"
  "counter.social"
  "coursehero.com"
  "covenantswatch.org.tw"
  "coze.com"
  "cpj.org"
  "cpu-monkey.com"
  "crackle.com"
  "crashlytics.com"
  "crazypool.org"
  "crazyshit.com"
  "crbug.com"
  "crchina.org"
  "creader.com"
  "creaders.net"
  "creativelab5.com"
  "cristyli.com"
  "crossfire.co.kr"
  "crossvpn.net"
  "crosswall.org"
  "croxyproxy.com"
  "crrev.com"
  "crucial.com"
  "crunchyroll.com"
  "cruxpool.com"
  "csdparty.com"
  "csis.org"
  "csmonitor.com"
  "css.pixnet.in"
  "csuchen.de"
  "csw.org.uk"
  "ct.org.tw"
  "ctinets.com"
  "ctinews.com"
  "ctinsider.com"
  "ctitv.com.tw"
  "ctowc.org"
  "cts.com.tw"
  "ctwant.com"
  "cuiweiping.net"
  "culture.tw"
  "cumlouder.com"
  "curvefish.com"
  "cusp.hk"
  "cutout.pro"
  "cutscenes.net"
  "cw.com.tw"
  "cyberghostvpn.com"
  "cynscribe.com"
  "d.cash"
  "d100.net"
  "d2pass.com"
  "dabr.co.uk"
  "dabr.me"
  "dabr.mobi"
  "dadazim.com"
  "dailymail.co.uk"
  "dailymotion.com"
  "dailysabah.com"
  "dailyview.tw"
  "dajiyuan.de"
  "dalailama.ru"
  "dalailamaworld.com"
  "dalianmeng.org"
  "daliulian.org"
  "danbooru.donmai.us"
  "danke4china.net"
  "darmau.co"
  "darpa.mil"
  "darrenliuwei.com"
  "dashlane.com"
  "data-vocabulary.org"
  "data18.com"
  "daum.net"
  "dawangidc.com"
  "daxa.cn"
  "dazn.com"
  "db.tt"
  "dbgjd.com"
  "dcard.tw"
  "dcs-spotify.megaphone.fm"
  "ddc.com.tw"
  "ddex.io"
  "deadhouse.org"
  "deadline.com"
  "debug.com"
  "deck.new"
  "decodet.co"
  "deepai.org"
  "deepmind.com"
  "deezer.com"
  "deja.com"
  "delcamp.net"
  "demo.unlock-music.dev"
  "demosisto.hk"
  "depositphotos.com"
  "desc.se"
  "desipro.de"
  "dessci.com"
  "deutsche-welle.de"
  "developers.box.net"
  "deviantart.com"
  "deviantart.net"
  "devio.us"
  "devpn.com"
  "devv.ai"
  "diaoyuislands.org"
  "digisfera.com"
  "diigo.com"
  "directcreative.com"
  "discoins.com"
  "disconnect.me"
  "discord.com"
  "discord.gg"
  "discordapp.com"
  "discordapp.net"
  "discuss.com.hk"
  "dish.com"
  "disk.yandex.com"
  "disk.yandex.ru"
  "disneyplus.com"
  "disp.cc"
  "disqus.com"
  "dit-inc.us"
  "diyin.org"
  "dizhuzhishang.com"
  "dl-laby.jp"
  "dl.box.net"
  "dlive.tv"
  "dlsite.com"
  "dlyoutube.com"
  "dm530.net"
  "dma.mil"
  "dmc.nico"
  "dmcdn.net"
  "dmhy.org"
  "dmm.co.jp"
  "dns.cloudflare.com"
  "dns.sb"
  "dns2go.com"
  "dnscrypt.org"
  "dnssec.net"
  "dnvod.tv"
  "doc.new"
  "docker.com"
  "docker.io"
  "dockerstatus.com"
  "docs.new"
  "documentingreality.com"
  "doh.sb"
  "dolc.de"
  "dolf.org.hk"
  "dongtaiwang.com"
  "dongtaiwang.net"
  "doom9.org"
  "doosho.com"
  "doourbest.org"
  "dot.sb"
  "dotplane.com"
  "dotsub.com"
  "dotvpn.com"
  "doub.io"
  "doubibackup.com"
  "doubiyunbackup.com"
  "doublethinklab.org"
  "douchi.space"
  "dougscripts.com"
  "doujincafe.com"
  "dowjones.io"
  "download.dappcdn.com"
  "download.futunn.com"
  "dpool.top"
  "dpp.org.tw"
  "dpr.info"
  "dragonex.io"
  "dragonsprings.org"
  "drgan.net"
  "dropbooks.tv"
  "dropbox.com"
  "dropboxapi.com"
  "dropboxusercontent.com"
  "dt18.com"
  "dtiblog.com"
  "dtic.mil"
  "dubox.com"
  "duck.com"
  "duckduckgo.com"
  "duckmylife.com"
  "duihua.org"
  "duihuahrjournal.org"
  "duplicati.com"
  "duyaoss.com"
  "dvdpac.com"
  "dvorak.org"
  "dw-world.com"
  "dw.com"
  "dw.de"
  "dweb.link"
  "dwnews.com"
  "dwnews.net"
  "dynawebinc.com"
  "dynu.com"
  "dysfz.cc"
  "e-classical.com.tw"
  "e-gold.com"
  "e-hentai.org"
  "e123.hk"
  "e621.net"
  "earthvpn.com"
  "eastasiaforum.org"
  "eastturkistangovernmentinexile.us"
  "ebook.hyread.com.tw"
  "ebtcbank.com"
  "ecfa.org.tw"
  "ecimg.tw"
  "economist.com"
  "edgecastcdn.net"
  "edigest.hk"
  "edubridge.com"
  "edx-cdn.org"
  "eesti.ee"
  "eevpn.com"
  "efksoft.com"
  "eic-av.com"
  "eireinikotaerukai.com"
  "eksisozluk.com"
  "elconfidencial.com"
  "elgoog.im"
  "elpais.com"
  "en.favotter.net"
  "encrypt.me"
  "encyclopedia.com"
  "enewstree.com"
  "englishfromengland.co.uk"
  "entermap.com"
  "epochhk.com"
  "epochtimes-bg.com"
  "epochtimes-romania.com"
  "epochtimes.co.il"
  "epochtimes.co.kr"
  "epochtimes.com"
  "epochtimes.com.tw"
  "epochtimes.de"
  "epochtimes.fr"
  "epochtimes.it"
  "epochtimes.jp"
  "epochtimes.ru"
  "epochtimes.se"
  "epochtimestr.com"
  "epochweek.com"
  "epochweekly.com"
  "eporner.com"
  "erights.net"
  "eriversoft.com"
  "ernestmandel.org"
  "erodaizensyu.com"
  "erodoujinlog.com"
  "erodoujinworld.com"
  "eromanga-kingdom.com"
  "eromangadouzin.com"
  "esg.t91y.com"
  "eslite.com"
  "esurance.com"
  "etherdelta.com"
  "ethermine.org"
  "etherscan.com"
  "etherscan.io"
  "etizer.org"
  "etokki.com"
  "etools.ncol.com"
  "etsy.com"
  "eurekavpt.com"
  "euronews.com"
  "evchk.wikia.com"
  "everipedia.org"
  "evschool.net"
  "exchristian.hk"
  "exhentai.org"
  "exmo.com"
  "exmormon.org"
  "expatshield.com"
  "expecthim.com"
  "expekt.com"
  "exploader.net"
  "expressnews.com"
  "expressvpn.com"
  "exrates.me"
  "extmatrix.com"
  "eyevio.jp"
  "eyny.com"
  "f-droid.org"
  "f2pool.com"
  "f8.com"
  "f95zone.to"
  "facebook.com"
  "facebook.de"
  "facebook.design"
  "facebook.hu"
  "facebook.in"
  "facebook.nl"
  "facebook.se"
  "facebookmail.com"
  "facebookquotes4u.com"
  "faceless.me"
  "facesofnyfw.com"
  "factchecklab.org"
  "factpedia.org"
  "faiththedog.info"
  "fakku.net"
  "fallenark.com"
  "falsefire.com"
  "falunasia.info"
  "falundafa-florida.org"
  "falundafa-nc.org"
  "falundafa-pa.net"
  "falundafaindia.org"
  "falunhr.org"
  "famunion.com"
  "fanbox.cc"
  "fangeqiang.com"
  "fanglizhi.info"
  "fangong.org"
  "fanhaolou.com"
  "fanqiang.network"
  "fanqiangdang.com"
  "fanqianghou.com"
  "fanqiangzhe.com"
  "fanswong.com"
  "fantv.hk"
  "fast.com"
  "fast.wistia.com"
  "fastestvpn.com"
  "fastpic.ru"
  "fastssh.com"
  "faststone.org"
  "fatbtc.com"
  "favstar.fm"
  "faz.net"
  "fb.com"
  "fb.me"
  "fb.watch"
  "fbaddins.com"
  "fbcdn.net"
  "fbsbx.com"
  "fbworkmail.com"
  "fc2cn.com"
  "feedburner.com"
  "feeder.co"
  "feedly.com"
  "feedx.net"
  "feelssh.com"
  "feixiaohao.com"
  "feministteacher.com"
  "fengzhenghu.com"
  "fengzhenghu.net"
  "fiddle.jshell.net"
  "figprayer.com"
  "fileflyer.com"
  "files.oaiusercontent.com"
  "filesor.com"
  "financetwitter.com"
  "financialexpress.com"
  "finchvpn.com"
  "findyoutube.com"
  "findyoutube.net"
  "firebaseio.com"
  "fireofliberty.info"
  "fireofliberty.org"
  "firetweet.io"
  "firstpost.com"
  "firstrade.com"
  "fish.audio"
  "flecheinthepeche.fr"
  "flexclip.com"
  "flexpool.io"
  "flgjustice.org"
  "flickr.com"
  "flipboard.com"
  "flipkart.com"
  "flitto.com"
  "flog.tw"
  "flowgpt.com"
  "flowhongkong.net"
  "flypool.org"
  "flyvpn.com"
  "flyzy2005.com"
  "fnac.be"
  "fnac.com"
  "fnc.ebc.net.tw"
  "fochk.org"
  "focustaiwan.tw"
  "fofg.org"
  "fooooo.com"
  "forbes.com"
  "forefront.ai"
  "foreignaffairs.com"
  "foreignpolicy.com"
  "form.new"
  "forms.new"
  "fountmedia.io"
  "fourthinternational.org"
  "foxsub.com"
  "fpmtmexico.org"
  "fqrouter.com"
  "frank2019.me"
  "franklc.com"
  "free-ss.site"
  "free.bg"
  "free.com.tw"
  "freebeacon.com"
  "freebrowser.org"
  "freechinaweibo.com"
  "freedom.gov"
  "freedomhouse.org"
  "freedominfonetweb.wordpress.com"
  "freedomsherald.org"
  "freegao.com"
  "freegpt.es"
  "freegpt.tech"
  "freehongkong.org"
  "freekazakhs.org"
  "freelotto.com"
  "freenetproject.org"
  "freeoz.org"
  "freess.org"
  "freessh.us"
  "freeterabox.com"
  "freetibet.org"
  "freetls.fastly.net"
  "freetribe.me"
  "freewallpaper4.me"
  "freewechat.com"
  "freeweibo.com"
  "freezhihu.org"
  "friendfeed.com"
  "friends-of-tibet.org"
  "friendsoftibet.org"
  "fril.jp"
  "fring.com"
  "fringenetwork.com"
  "frommel.net"
  "frontlinedefenders.org"
  "frootvpn.com"
  "froth.zone"
  "fscked.org"
  "ft.com"
  "ftchinese.com"
  "ftv.com.tw"
  "ftvnews.com.tw"
  "ftx.com"
  "fuchsia.dev"
  "fuckccp.com"
  "fuckccp.xyz"
  "fullerconsideration.com"
  "fullservicegame.com"
  "funkyimg.com"
  "furbo.org"
  "furinkan.com"
  "furrybar.com"
  "futu.cn"
  "futu.com"
  "futu.link"
  "futu0.com"
  "futu1.com"
  "futu2.com"
  "futu3.com"
  "futu4.com"
  "futu5.com"
  "futu6.com"
  "futu7.com"
  "futu8.com"
  "futu9.com"
  "futuau.com"
  "futubull.cn"
  "futuchain.com"
  "futuesop.com"
  "futufin.com"
  "futuhk.com"
  "futuhk2.com"
  "futuhkapp.com"
  "futuhn.com"
  "futuholdings.com"
  "futuinc.com"
  "futuniuniu.com"
  "futunn.com"
  "futuremessage.org"
  "futustatic.com"
  "fututrade.com"
  "fututrustee.com"
  "fw.cm"
  "fxcm-chinese.com"
  "fxnetworks.com"
  "g-area.org"
  "g-queen.com"
  "g.ai"
  "g.co"
  "g0v.social"
  "gab.com"
  "gabocorp.com"
  "gagaoolala.com"
  "galenwu.com"
  "game735.com"
  "gamer.com.tw"
  "gamez.com.tw"
  "ganjing.com"
  "ganjingworld.com"
  "gaoming.net"
  "gartlive.com"
  "garudalinux.org"
  "gate.com"
  "gate.io"
  "gatecoin.com"
  "gather.com"
  "gaymap.cc"
  "gazotube.com"
  "gcc.org.hk"
  "gclubs.com"
  "gcmasia.com"
  "gcr.io"
  "gdaily.org"
  "geek-art.net"
  "gekikame.com"
  "gencraft.com"
  "generated.photos"
  "genius.com"
  "geph.io"
  "get.app"
  "get.dappcdn.com"
  "get.dev"
  "get.how"
  "get.page"
  "getastrill.com"
  "getcloak.com"
  "getfoxyproxy.org"
  "getgom.com"
  "geti2p.net"
  "getlantern.org"
  "getmalus.com"
  "getmdl.io"
  "getoutline.org"
  "getsession.org"
  "getsync.com"
  "gettr.com"
  "gettyimages.ae"
  "gettyimages.ca"
  "gettyimages.de"
  "gettyimages.hk"
  "gettyimages.in"
  "gettyimages.it"
  "gettyimages.us"
  "getuploader.com"
  "gfsale.com"
  "gfw.press"
  "gfw.report"
  "gfwatch.org"
  "gfwbao.com"
  "ggpht.com"
  "ggssl.com"
  "ghidra-sre.org"
  "ghostpath.com"
  "ghut.org"
  "giga-web.jp"
  "girlbanker.com"
  "git.io"
  "gitbook.io"
  "github.blog"
  "github.com"
  "github.io"
  "githubassets.com"
  "githubcopilot.com"
  "githubusercontent.com"
  "gitlab.net"
  "gizlen.net"
  "gjczz.com"
  "glarity.app"
  "glass8.eu"
  "gle"
  "global.bing.com"
  "global.ssl.fastly.net"
  "globaljihad.net"
  "globalrescue.net"
  "globalvoices.org"
  "globalvoicesonline.org"
  "globalvpn.net"
  "glorystar.me"
  "glype.com"
  "gmail.com"
  "gmgard.com"
  "gmgn.ai"
  "gmodules.com"
  "gnci.org.hk"
  "gnews.org"
  "go-to-zlibrary.se"
  "go141.com"
  "go5.dev"
  "goagent.biz"
  "godaddy.com"
  "godfootsteps.org"
  "godoc.org"
  "gofundme.com"
  "gohappy.com.tw"
  "golang.org"
  "goldbetsports.com"
  "golden-ages.org"
  "goldeneyevault.com"
  "goldenfrog.com"
  "goldwave.com"
  "gongm.in"
  "goo.gl"
  "goo.ne.jp"
  "gooday.xyz"
  "goodhope.school"
  "goodnewsnetwork.org"
  "goodreaders.com"
  "goodreads.com"
  "goofind.com"
  "goog"
  "google"
  "google.ac"
  "google.ad"
  "google.ae"
  "google.af"
  "google.ai"
  "google.al"
  "google.am"
  "google.as"
  "google.at"
  "google.az"
  "google.ba"
  "google.be"
  "google.bf"
  "google.bg"
  "google.bi"
  "google.bj"
  "google.bs"
  "google.bt"
  "google.by"
  "google.ca"
  "google.cat"
  "google.cd"
  "google.cf"
  "google.cg"
  "google.ch"
  "google.ci"
  "google.cl"
  "google.cm"
  "google.co.ao"
  "google.co.bw"
  "google.co.ck"
  "google.co.cr"
  "google.co.id"
  "google.co.il"
  "google.co.in"
  "google.co.jp"
  "google.co.ke"
  "google.co.kr"
  "google.co.ls"
  "google.co.ma"
  "google.co.mz"
  "google.co.nz"
  "google.co.th"
  "google.co.tz"
  "google.co.ug"
  "google.co.uk"
  "google.co.uz"
  "google.co.ve"
  "google.co.vi"
  "google.co.za"
  "google.co.zm"
  "google.co.zw"
  "google.com"
  "google.com.af"
  "google.com.ag"
  "google.com.ai"
  "google.com.ar"
  "google.com.au"
  "google.com.bd"
  "google.com.bh"
  "google.com.bn"
  "google.com.bo"
  "google.com.br"
  "google.com.bz"
  "google.com.co"
  "google.com.cu"
  "google.com.cy"
  "google.com.do"
  "google.com.ec"
  "google.com.eg"
  "google.com.et"
  "google.com.fj"
  "google.com.gh"
  "google.com.gi"
  "google.com.gt"
  "google.com.hk"
  "google.com.jm"
  "google.com.kh"
  "google.com.kw"
  "google.com.lb"
  "google.com.ly"
  "google.com.mm"
  "google.com.mt"
  "google.com.mx"
  "google.com.my"
  "google.com.na"
  "google.com.nf"
  "google.com.ng"
  "google.com.ni"
  "google.com.np"
  "google.com.om"
  "google.com.pa"
  "google.com.pe"
  "google.com.pg"
  "google.com.ph"
  "google.com.pk"
  "google.com.pr"
  "google.com.py"
  "google.com.qa"
  "google.com.sa"
  "google.com.sb"
  "google.com.sg"
  "google.com.sl"
  "google.com.sv"
  "google.com.tj"
  "google.com.tr"
  "google.com.tw"
  "google.com.ua"
  "google.com.uy"
  "google.com.vc"
  "google.com.vn"
  "google.cv"
  "google.cz"
  "google.de"
  "google.dev"
  "google.dk"
  "google.dm"
  "google.dz"
  "google.ee"
  "google.es"
  "google.eu"
  "google.fi"
  "google.fm"
  "google.fr"
  "google.ga"
  "google.ge"
  "google.gg"
  "google.gl"
  "google.gm"
  "google.gp"
  "google.gr"
  "google.gy"
  "google.hk"
  "google.hn"
  "google.hr"
  "google.ht"
  "google.hu"
  "google.ie"
  "google.im"
  "google.iq"
  "google.is"
  "google.it"
  "google.it.ao"
  "google.je"
  "google.jo"
  "google.kg"
  "google.ki"
  "google.kz"
  "google.la"
  "google.li"
  "google.lk"
  "google.lt"
  "google.lu"
  "google.lv"
  "google.md"
  "google.me"
  "google.mg"
  "google.mk"
  "google.ml"
  "google.mn"
  "google.ms"
  "google.mu"
  "google.mv"
  "google.mw"
  "google.mx"
  "google.ne"
  "google.nl"
  "google.no"
  "google.nr"
  "google.nu"
  "google.org"
  "google.pl"
  "google.pn"
  "google.ps"
  "google.pt"
  "google.ro"
  "google.rs"
  "google.ru"
  "google.rw"
  "google.sc"
  "google.se"
  "google.sh"
  "google.si"
  "google.sk"
  "google.sm"
  "google.sn"
  "google.so"
  "google.sr"
  "google.st"
  "google.td"
  "google.tg"
  "google.tk"
  "google.tl"
  "google.tm"
  "google.tn"
  "google.to"
  "google.tt"
  "google.us"
  "google.vg"
  "google.vn"
  "google.vu"
  "google.ws"
  "googleapis.com"
  "googleapps.com"
  "googlearth.com"
  "googleartproject.com"
  "googleblog.com"
  "googlebot.com"
  "googlechinawebmaster.com"
  "googlecode.com"
  "googlecommerce.com"
  "googledomains.com"
  "googledrive.com"
  "googleearth.com"
  "googlefiber.net"
  "googlegroups.com"
  "googlehosted.com"
  "googleideas.com"
  "googleinsidesearch.com"
  "googlemail.com"
  "googlemashups.com"
  "googlepagecreator.com"
  "googleplay.com"
  "googleplus.com"
  "googlescholar.com"
  "googlesource.com"
  "googleusercontent.com"
  "googlevideo.com"
  "googleweblight.com"
  "googlezip.net"
  "gopetition.com"
  "goreforum.com"
  "goregrish.com"
  "gospelherald.com"
  "gotdns.ch"
  "gotquestions.org"
  "gotrusted.com"
  "gotw.ca"
  "gov.ir"
  "gov.taipei"
  "gov.tw"
  "grammaly.com"
  "graph.org"
  "graphis.ne.jp"
  "graphql.org"
  "gravatar.com"
  "greasyfork.org"
  "greatfire.org"
  "greatfire.us7.list-manage.com"
  "greatfirevpn.com"
  "greatfirewallofchina.org"
  "greenpeace.org"
  "greenvpn.net"
  "grindr.com"
  "grok.com"
  "grokipedia.com"
  "ground.news"
  "gsearch.media"
  "gsp.target.com"
  "gstatic.com"
  "gtricks.com"
  "gtv.org"
  "gtv1.org"
  "guangming.com.my"
  "guishan.org"
  "gumroad.com"
  "gunsamerica.com"
  "gutteruncensored.com"
  "gvm.com.tw"
  "gvt1.com"
  "gvt3.com"
  "gwins.org"
  "gwtproject.org"
  "gzone-anime.info"
  "h-china.org"
  "hackmd.io"
  "hackthatphone.net"
  "haijiao.com"
  "haiwaikan.com"
  "hakkatv.org.tw"
  "halktv.com.tr"
  "hanime.tv"
  "hanime1.me"
  "hardsextube.com"
  "hautelook.com"
  "hautelookcdn.com"
  "hbg.com"
  "hbo.com"
  "hbomax.com"
  "hdtvb.net"
  "heartyit.com"
  "hecaitou.net"
  "hechaji.com"
  "heeact.edu.tw"
  "helixstudios.net"
  "helloandroid.com"
  "helloqueer.com"
  "help.byspotify.com"
  "helpeachpeople.com"
  "helpster.de"
  "hembed.com"
  "heqinglian.net"
  "heritage.org"
  "herokuapp.com"
  "herominers.com"
  "hexieshe.com"
  "hexieshe.xyz"
  "hexxeh.net"
  "heyuedi.com"
  "hicairo.com"
  "hiccears.com"
  "hidden-advent.org"
  "hiddify.com"
  "hide.me"
  "hideipvpn.com"
  "hideman.net"
  "hidemy.name"
  "hidemyass.com"
  "hidemycomp.com"
  "highrockmedia.com"
  "hiitch.com"
  "hikinggfw.org"
  "himalayan-foundation.org"
  "himemix.com"
  "hindustantimes.com"
  "hinet.net"
  "hitbtc.com"
  "hive.blog"
  "hiveon.net"
  "hk.jiepang.com"
  "hk01.com"
  "hka8964.wordpress.com"
  "hkanews.wordpress.com"
  "hkbookcity.com"
  "hkchronicles.com"
  "hkcnews.com"
  "hkcoc.com"
  "hkdc.us"
  "hket.com"
  "hkfaa.com"
  "hkgalden.com"
  "hkgolden.com"
  "hkgpao.com"
  "hklts.org.hk"
  "hkmap.live"
  "hkong.hk"
  "hkopentv.com"
  "hkpeanut.com"
  "hkreporter.com"
  "hmoegirl.com"
  "hmvdigital.ca"
  "hmvdigital.com"
  "hnjhj.com"
  "hojemacau.com.mo"
  "hola.com"
  "hola.org"
  "hole.thu.monster"
  "holyspiritspeaks.org"
  "home.saxo"
  "homedepot.com"
  "hongkong.fandom.com"
  "hongkongfp.com"
  "hongzhi.li"
  "honven.xyz"
  "hootsuite.com"
  "hoover.org"
  "hoovers.com"
  "horrorporn.com"
  "hostloc.com"
  "hotair.com"
  "hotcoin.com"
  "hotspotshield.com"
  "hottg.com"
  "hotvpn.com"
  "howtoforge.com"
  "hoxx.com"
  "hoy.tv"
  "hpjav.com"
  "hqcdp.org"
  "hqjapanesesex.com"
  "hqsbnet.wordpress.com"
  "hqsbonline.wordpress.com"
  "hrichina.org"
  "hrntt.org"
  "hrw.org"
  "hsex.men"
  "hsjp.net"
  "hsselite.com"
  "hst.net.tw"
  "htkou.net"
  "html5rocks.com"
  "htx.com"
  "huaglad.com"
  "huanghuagang.org"
  "huaren.us"
  "huayuworld.org"
  "hudatoriq.web.id"
  "hudson.org"
  "huffingtonpost.com"
  "huffpost.com"
  "huggingface.co"
  "hugoroy.eu"
  "huhaitai.com"
  "huhamhire.com"
  "huhangfei.com"
  "hulu.com"
  "huluim.com"
  "humanparty.me"
  "humanrightspressawards.org"
  "hung-ya.com"
  "huobi.co"
  "huobi.com"
  "huobi.li"
  "huobi.me"
  "huobi.pro"
  "huobi.sc"
  "huobipool.com"
  "huobipro.com"
  "huping.net"
  "hutianyi.net"
  "hwayue.org.tw"
  "hxwk.org"
  "hybrid-analysis.com"
  "hyperbeam.com"
  "hyperrate.com"
  "hypothes.is"
  "i.111666.best"
  "i.lithium.com"
  "i2p2.de"
  "i818hk.com"
  "iam.soy"
  "iask.ca"
  "iavian.net"
  "ibvpn.com"
  "icedrive.net"
  "icij.org"
  "icl-fi.org"
  "icoco.com"
  "iconpaper.org"
  "icu-project.org"
  "id.heroku.com"
  "idcflare.com"
  "identi.ca"
  "idiomconnection.com"
  "idope.se"
  "ifan.cz.cc"
  "ifcss.org"
  "ifreechina.wordpress.com"
  "ifreewares.com"
  "ift.tt"
  "igcd.net"
  "igfw.net"
  "igoogle.com"
  "igvita.com"
  "iicns.com"
  "ilbe.com"
  "ilhamtohtiinstitute.org"
  "illawarramercury.com.au"
  "illusionfactory.com"
  "ilove80.be"
  "ilovelongtoes.com"
  "im88.tw"
  "imagefap.com"
  "imageflea.com"
  "imageglass.org"
  "images-gaytube.com"
  "images.prismic.io"
  "imageshack.us"
  "imagevenue.com"
  "imagezilla.net"
  "imago-images.com"
  "img.ly"
  "img.picgo.net"
  "imgasd.com"
  "imgchili.net"
  "imgur.com"
  "imkev.com"
  "imlive.co"
  "improd.works"
  "incloak.com"
  "incredibox.fr"
  "independent.co.uk"
  "india.com"
  "indiablooms.com"
  "indianarrative.com"
  "indiandefensenews.in"
  "indiatoday.in"
  "indiemerch.com"
  "inews-api.tvb.com"
  "info-graf.fr"
  "infosec.exchange"
  "infura.io"
  "inherit.live"
  "initiativesforchina.org"
  "inkbunny.net"
  "inkui.com"
  "inmediahk.net"
  "inoreader.com"
  "inote.tw"
  "insecam.org"
  "inside.com.tw"
  "insidevoa.com"
  "instagram.com"
  "institut-tibetain.org"
  "interactivebrokers.com"
  "internet.org"
  "internetfreedom.org"
  "internetpopculture.com"
  "interseclab.org"
  "inthenameofconfuciusmovie.com"
  "investigating.wordpress.com"
  "investing.com"
  "invidio.us"
  "inxian.com"
  "ipdefenseforum.com"
  "ipfire.org"
  "ipfs.4everland.io"
  "ipfs.io"
  "iphone4hongkong.com"
  "iphonetaiwan.org"
  "iphonix.fr"
  "ipicture.ru"
  "ipify.org"
  "ipjetable.net"
  "ippotv.com"
  "ipredator.se"
  "iptvbin.com"
  "ipvanish.com"
  "irangov.ir"
  "irna.ir"
  "ironpython.net"
  "ironsocket.com"
  "isaacmao.com"
  "isc.sans.edu"
  "isgreat.org"
  "ishr.ch"
  "islamhouse.com"
  "ismaelan.com"
  "ismprofessional.net"
  "israbox.com"
  "issues.chromium.org"
  "issuu.com"
  "isupportuyghurs.org"
  "italiatibet.org"
  "itasoftware.com"
  "itch.io"
  "itemfix.com"
  "itiger.com"
  "itigerup.com"
  "itshidden.com"
  "iuhrdf.org"
  "ivacy.com"
  "ivonblog.com"
  "ivpn.net"
  "iwara.tv"
  "ixquick.com"
  "iyouport.com"
  "iyouport.org"
  "j.mp"
  "jable.tv"
  "jamestown.org"
  "jamyangnorbu.com"
  "jan.ai"
  "japan-whores.com"
  "japanhdv.com"
  "japantimes.co.jp"
  "jav321.com"
  "javakiba.org"
  "javbus.com"
  "javdb.com"
  "javfinder.ai"
  "javfor.me"
  "javhub.net"
  "javhuge.com"
  "javlibrary.com"
  "javmobile.net"
  "javseen.com"
  "jcpenney.com"
  "jex.com"
  "jgoodies.com"
  "jhelab.org"
  "jiangweiping.com"
  "jiaoyou8.com"
  "jifangge.com"
  "jiji.com"
  "jims.net"
  "jingpin.org"
  "jinrizhiyi.news"
  "jintian.net"
  "jinx.com"
  "jitouch.com"
  "jma.go.jp"
  "jmsc.hku.hk"
  "joachims.org"
  "jobnewera.wordpress.com"
  "joinclubhouse.com"
  "joinmastodon.org"
  "jornaldacidadeonline.com.br"
  "journalofdemocracy.org"
  "jpl.nasa.gov"
  "jsdelivr.net"
  "jtvnw.net"
  "jukujo-club.com"
  "juliepost.com"
  "juliereyc.com"
  "junauza.com"
  "justhost.ru"
  "justmysocks.net"
  "justmysocks1.net"
  "justmysockscn.com"
  "juziyue.com"
  "ka-wai.com"
  "kadokawa.co.jp"
  "kagyu.org.za"
  "kagyuoffice.org"
  "kagyuoffice.org.tw"
  "kakao.com"
  "kanald.com.tr"
  "kannewyork.com"
  "kanshifang.com"
  "kantie.org"
  "kaotic.com"
  "karayou.com"
  "kathmandupost.com"
  "kawaiikawaii.jp"
  "kawase.com"
  "kb.monitorware.com"
  "kebrum.com"
  "kendatire.com"
  "kenengba.com"
  "kepard.com"
  "kex.com"
  "keycdn.com"
  "kfor.com"
  "khatrimaza.org"
  "kichiku-doujinko.com"
  "kik.com"
  "killwall.com"
  "kindle4rss.com"
  "kingdomsalvation.org"
  "kingkong.com.tw"
  "kingstone.com.tw"
  "kinmen.org.tw"
  "kinmen.travel"
  "kinokuniya.com"
  "kk-whys.co.jp"
  "kkbox.com"
  "kknews.cc"
  "knowyourmeme.com"
  "kobo.com"
  "kobobooks.com"
  "kompozer.net"
  "konachan.com"
  "koolsolutions.com"
  "koornk.com"
  "koranmandarin.com"
  "kpkuang.org"
  "kqes.net"
  "kraken.com"
  "kspcoin.com"
  "ktzhk.com"
  "kuaichedao.co"
  "kucoin.com"
  "kukuku.uk"
  "kurtmunger.com"
  "kwcg.ca"
  "kwongwah.com.my"
  "kxsw.life"
  "kzaobao.com"
  "kzeng.info"
  "lab.skk.moe"
  "labiennale.org"
  "lagranepoca.com"
  "lala.im"
  "lama.com.tw"
  "lamayeshe.com"
  "lamnia.co.uk"
  "landofhope.tv"
  "lantern.io"
  "laogai.org"
  "laogairesearch.org"
  "laohu8.com"
  "laqingdan.net"
  "larsgeorge.com"
  "lastfm.es"
  "lausan.hk"
  "lbank.info"
  "lbctrl.com"
  "lbkrs.com"
  "ldplayer.net"
  "ldplayer.tw"
  "le-vpn.com"
  "leafyvpn.net"
  "lecloud.net"
  "ledger.com"
  "left21.hk"
  "legra.ph"
  "leisurepro.com"
  "lematin.ch"
  "lemonde.fr"
  "lenwhite.com"
  "leonardo.ai"
  "lesoir.be"
  "letscorp.net"
  "lexica.art"
  "li.taipei"
  "liangyou.net"
  "liangzhichuanmei.com"
  "liaowangxizang.net"
  "liberal.org.hk"
  "libertysculpturepark.com"
  "libertytimes.com.tw"
  "libgen.is"
  "library-access.sk"
  "libredd.it"
  "lifemiles.com"
  "lighten.org.tw"
  "lighti.me"
  "lightnovel.cn"
  "lightyearvpn.com"
  "lih.kg"
  "lihkg.com"
  "like.com"
  "lilaoshibushinilaoshi.com"
  "line-apps.com"
  "line-scdn.net"
  "line.me"
  "line.naver.jp"
  "linear-abematv.akamaized.net"
  "lingualeo.com"
  "lingvodics.com"
  "linkedin.com"
  "linktr.ee"
  "linux.do"
  "linux.org.hk"
  "liquiditytp.com"
  "liquidvpn.com"
  "listennotes.com"
  "listentoyoutube.com"
  "litenews.hk"
  "liuxiaobo.net"
  "liuxiaotong.com"
  "livecoin.net"
  "liveleak.com"
  "livemint.com"
  "livestream.com"
  "livevideo.com"
  "livingstream.com"
  "lmarena.ai"
  "localbitcoins.com"
  "localdomain.ws"
  "lockestek.com"
  "login.target.com"
  "logos.com.hk"
  "longbridge.cloud"
  "longbridge.com"
  "longbridge.global"
  "longbridge.hk"
  "longbridge.sg"
  "longbridgeapp.com"
  "longbridgehk.com"
  "longportapp.cn"
  "longportapp.com"
  "longtermly.net"
  "longtoes.com"
  "lookpic.com"
  "lovart.ai"
  "lovetvshow.com"
  "lpsg.com"
  "lrfz.com"
  "lrip.org"
  "lsd.org.hk"
  "lsm.org"
  "lsmchinese.org"
  "lsmkorean.org"
  "lt.sntp.uk"
  "ltn.com.tw"
  "luckydesigner.space"
  "luckymobile.ca"
  "ludepress.com"
  "lupm.org"
  "lushstories.com"
  "lvhai.org"
  "lvv2.com"
  "lzjscript.com"
  "lzmtnews.org"
  "m.me"
  "m.moegirl.org"
  "macgamestore.com"
  "mad-ar.ch"
  "madewithcode.com"
  "madonna-av.com"
  "madou.club"
  "madrau.com"
  "madthumbs.com"
  "mahjongsoul.com"
  "main-ecnpaper-economist.content.pugpig.com"
  "makemymood.com"
  "mandiant.com"
  "mangabz.com"
  "mangafox.com"
  "mangafox.me"
  "mangmang.run"
  "manta.com"
  "manus.im"
  "manyvoices.news"
  "marc.info"
  "martau.com"
  "marxist.net"
  "marxists.org"
  "mas.to"
  "mastodon.cloud"
  "mastodon.host"
  "mastodon.online"
  "mastodon.social"
  "mastodon.xyz"
  "matainja.com"
  "material.io"
  "matome-plus.com"
  "matome-plus.net"
  "matrix.org"
  "matters.news"
  "matters.town"
  "matthewdgreen.wordpress.com"
  "mattwilcox.net"
  "maven.neoforged.net"
  "mcadforums.com"
  "mcusercontent.com"
  "md-t.org"
  "me.me"
  "me.ns.ci"
  "meansys.com"
  "media.nu.nl"
  "mediachinese.com"
  "mediafreakcity.com"
  "mediamatters.org"
  "mediawiki.org"
  "medium.com"
  "meee.com.tw"
  "mega.co.nz"
  "mega.io"
  "mega.nz"
  "megalodon.jp"
  "megaproxy.com"
  "megurineluka.com"
  "meizhong.blog"
  "meizhong.report"
  "memehk.com"
  "memes.tw"
  "mercari.com"
  "mercari.jp"
  "mercatox.com"
  "mercdn.net"
  "mercyprophet.org"
  "mergersandinquisitions.com"
  "meridian-trust.org"
  "meripet.com"
  "merit-times.com.tw"
  "messenger.com"
  "meta.com"
  "metafilter.com"
  "metamask.io"
  "metart.com"
  "metarthunter.com"
  "meteorshowersonline.com"
  "metro.taipei"
  "metrolife.ca"
  "metroradio.com.hk"
  "mewe.com"
  "mfxmedia.com"
  "mgoon.com"
  "mgstage.com"
  "mh4u.org"
  "mhwindow.org"
  "microvpn.com"
  "mihua.org"
  "mij.rip"
  "mikanani.me"
  "mike.cz.cc"
  "mikesoltys.com"
  "mingdemedia.org"
  "minghui-school.org"
  "minghui.or.kr"
  "minghui.org"
  "minghuiyw.wordpress.com"
  "mingjinglishi.com"
  "mingjingnews.com"
  "mingjingtimes.com"
  "mingpao.com"
  "mingpaocanada.com"
  "mingpaomonthly.com"
  "mingpaonews.com"
  "mingshengbao.com"
  "minhhue.net"
  "miningpoolhub.com"
  "ministrybooks.org"
  "minzhuzhongguo.org"
  "miraheze.org"
  "miroguide.com"
  "mirror.xyz"
  "mirrorbooks.com"
  "mirrormedia.mg"
  "missav.com"
  "missav.ws"
  "mistral.ai"
  "mitbbs.com"
  "miuipolska.pl"
  "mixero.com"
  "mixi.jp"
  "mixx.com"
  "mizzmona.com"
  "mji.rip"
  "mjj.rip"
  "mjj.today"
  "mlc.ai"
  "mlzs.work"
  "mmaaxx.com"
  "mobatek.net"
  "mobile01.com"
  "mobileways.de"
  "mod.io"
  "modernchinastudies.org"
  "moeerolibrary.com"
  "moeshare.cc"
  "mog.com"
  "mohu.club"
  "mohu.rocks"
  "mojim.com"
  "momoshop.com.tw"
  "mondex.org"
  "money-link.com.tw"
  "moneydj.com"
  "monica.im"
  "monitorchina.org"
  "monocloud.me"
  "monster.com"
  "moodyz.com"
  "moomoo.com"
  "moomooequity.com"
  "moomootrustee.com"
  "moon.fm"
  "moonbbs.com"
  "moonbingo.com"
  "moptt.tw"
  "moresci.sale"
  "morningsun.org"
  "mos.ru"
  "mosavi.io"
  "movements.org"
  "moviefap.com"
  "mozilla.ai"
  "mpettis.com"
  "mpfinance.com"
  "mpinews.com"
  "mrtweet.com"
  "msa-it.org"
  "msha.gov"
  "mstdn.social"
  "mthruf.com"
  "mubi.com"
  "mullvad.net"
  "multiply.com"
  "music.amazon.com"
  "musixmatch.com"
  "muzi.com"
  "muzi.net"
  "muzu.tv"
  "mvg.jp"
  "my-private-network.co.uk"
  "my.pcloud.com"
  "myaudiocast.com"
  "mybet.com"
  "mychinanews.com"
  "mycnnews.com"
  "myeclipseide.com"
  "myiphide.com"
  "myjs.tw"
  "mykomica.org"
  "mymoe.moe"
  "myparagliding.com"
  "mypikpak.com"
  "mypopescu.com"
  "myspacecdn.com"
  "mytvsuper.com"
  "mywife.cc"
  "naacoalition.org"
  "naitik.net"
  "nakedsecurity.sophos.com"
  "nakido.com"
  "nalandabodhi.org"
  "nalandawest.org"
  "namu.wiki"
  "nanopool.org"
  "nanyang.com"
  "nanyangpost.com"
  "nat.moe"
  "national-lottery.co.uk"
  "nationalawakening.org"
  "nationalinterest.org"
  "nationalreview.com"
  "nationwide.com"
  "naughtyamerica.com"
  "naver.com"
  "navyfamily.navy.mil"
  "navyreserve.navy.mil"
  "nbcnews.com"
  "nbyy.tv"
  "nchrd.org"
  "ncn.org"
  "ndi.org"
  "nekoslovakia.net"
  "neo-miracle.com"
  "neodb.social"
  "neowin.net"
  "nephobox.com"
  "netalert.me"
  "netflav.com"
  "netflix.com"
  "netflix.net"
  "netlify.app"
  "netme.cc"
  "netsarang.com"
  "newchen.com"
  "newhighlandvision.com"
  "newindianexpress.com"
  "newmitbbs.com"
  "news.ebc.net.tw"
  "news.mt.co.kr"
  "news.seehua.com"
  "news.tvbs.com.tw"
  "news.ycombinator.com"
  "news1.kr"
  "news18.com"
  "newsancai.com"
  "newsblur.com"
  "newshub.co.nz"
  "newsmax.com"
  "newstamago.com"
  "newstapa.org"
  "newstatesman.com"
  "newstimes.com"
  "newsweek.com"
  "newtalk.tw"
  "newthuhole.com"
  "newyorker.com"
  "nexon.com"
  "nextdigital.com.hk"
  "nexton-net.jp"
  "nexttv.com.tw"
  "nf.id.au"
  "nflxext.com"
  "nflximg.com"
  "nflximg.net"
  "nflxso.net"
  "nflxvideo.net"
  "nfsc.press"
  "nfscofficial.com"
  "nftstorage.link"
  "nga.mil"
  "nhentai.net"
  "nic.cz.cc"
  "nic.gov"
  "nicovideo.jp"
  "nightswatch.top"
  "nikke-en.com"
  "nikke-jp.com"
  "nikke-kr.com"
  "nikke.hotcool.tw"
  "nikkei.com"
  "ninjaproxy.ninja"
  "nirsoft.net"
  "nitter.cc"
  "nitter.net"
  "niu.moe"
  "niusnews.com"
  "njactb.org"
  "nlfreevpn.com"
  "nmsl.website"
  "nnews.eu"
  "nobel.se"
  "nodeseek.com"
  "nokogiri.org"
  "nokola.com"
  "nordstrom.com"
  "nordstromimage.com"
  "nordstromrack.com"
  "nordvpn.com"
  "nos.nl"
  "notepad-plus-plus.org"
  "nottinghampost.com"
  "now.com"
  "nownews.com"
  "noxinfluencer.com"
  "npa.go.jp"
  "npsboost.com"
  "nrk.no"
  "ntd.tv"
  "ntdtv.com"
  "ntdtv.com.tw"
  "ntdtv.cz"
  "nuexpo.com"
  "nurgo-software.com"
  "nusatrip.com"
  "nutaku.net"
  "nutsvpn.work"
  "nuuvem.com"
  "nvdst.com"
  "nyaa.si"
  "nybooks.com"
  "nypost.com"
  "nyt.com"
  "nytcn.me"
  "nytco.com"
  "nytimes.com"
  "nytimes.map.fastly.net"
  "nytimg.com"
  "nytstyle.com"
  "o3o.ca"
  "oanda.com"
  "oann.com"
  "obyte.org"
  "october-review.org"
  "octocaptcha.com"
  "oculus.com"
  "oculuscdn.com"
  "odysee.com"
  "oex.com"
  "officeoftibet.com"
  "ogaoga.org"
  "ogate.org"
  "ohmyrss.com"
  "ok.ru"
  "okayfreedom.com"
  "okcoin.com"
  "okex.com"
  "okk.tw"
  "oklink.com"
  "okpool.me"
  "okx.com"
  "olehdtv.com"
  "olelive.com"
  "olevod.com"
  "olumpo.com"
  "omct.org"
  "omni7.jp"
  "omnitalk.com"
  "omnitalk.org"
  "omny.fm"
  "on.cc"
  "on2.com"
  "onapp.com"
  "one.one.one.one"
  "onedrive.com"
  "onedrive.live.com"
  "onejav.com"
  "onevps.com"
  "onion.city"
  "onion.ly"
  "onlineyoutube.com"
  "onlygayvideo.com"
  "ontrac.com"
  "oojj.de"
  "ooni.io"
  "ooni.org"
  "open.firstory.me"
  "openai.com"
  "openapi-quote.longbridge.cn"
  "openapi-quote.longbridge.com"
  "openapi-trade.longbridge.cn"
  "openapi-trade.longbridge.com"
  "openapi.futunn.com"
  "openapi.longbridge.cn"
  "openapi.longbridge.com"
  "openart.ai"
  "opencritic.com"
  "opendemocracy.net"
  "openid.net"
  "openleaks.org"
  "opensea.io"
  "openstreetmap.org"
  "opentech.fund"
  "openvpn.net"
  "openvpn.org"
  "openwebster.com"
  "ordns.he.net"
  "oricon.co.jp"
  "orient-doll.com"
  "orientaldaily.com.my"
  "orn.jp"
  "osfoora.com"
  "osmand.net"
  "otcbtc.com"
  "otto.de"
  "ourdearamy.com"
  "oursteps.com.au"
  "ourtv.hk"
  "overcast.fm"
  "overdaily.org"
  "overdrive.com"
  "overplay.net"
  "oversea.istarshine.com"
  "ovpn.com"
  "ow.ly"
  "owltail.com"
  "oxfordscholarship.com"
  "ozvoice.org"
  "pachosting.com"
  "pacom.mil"
  "pacopacomama.com"
  "page.link"
  "paimon.moe"
  "pancakeswap.finance"
  "pandafan.pub"
  "pandapow.co"
  "pandavpn-jp.com"
  "pandavpnpro.com"
  "pandora.com"
  "panoramio.com"
  "pao-pao.net"
  "parkansky.com"
  "parler.com"
  "parse.com"
  "parsevideo.com"
  "partnerstack.xyz"
  "passion.com"
  "paste.ee"
  "pastie.org"
  "patreon.com"
  "patreonusercontent.com"
  "pawoo.net"
  "paxful.com"
  "payments-jp.amazon.com"
  "pbs.org"
  "pbworks.com"
  "pbxes.com"
  "pbxes.org"
  "pcgamesn.com"
  "pcgamestorrents.com"
  "pcij.org"
  "pct.org.tw"
  "pdproxy.com"
  "pds.nasa.gov"
  "pdst.fm"
  "peace.ca"
  "peing.net"
  "pekingduck.org"
  "pen.io"
  "pendrivelinux.com"
  "penguin.com.au"
  "pentoy.hk"
  "peoplenews.tw"
  "peopo.org"
  "perfect-privacy.com"
  "periscope.tv"
  "perma.cc"
  "perplexity.ai"
  "pewresearch.org"
  "phayul.com"
  "phmsociety.org"
  "phncdn.com"
  "phosphation13.rssing.com"
  "photodharma.net"
  "photofocus.com"
  "photonmedia.net"
  "piaotia.com"
  "picacomic.com"
  "picacomiccn.com"
  "picasaweb.com"
  "picsart.com"
  "picuki.com"
  "pigav.com"
  "pin-cong.com"
  "pin6.com"
  "pincong.rocks"
  "ping.fm"
  "pinimg.com"
  "pinoy-n.com"
  "pinterest.at"
  "pinterest.ca"
  "pinterest.cl"
  "pinterest.co.uk"
  "pinterest.com"
  "pinterest.com.au"
  "pinterest.com.mx"
  "pinterest.de"
  "pinterest.es"
  "pinterest.fr"
  "pinterest.ie"
  "pinterest.it"
  "pinterest.jp"
  "pinterest.nz"
  "pinterest.ph"
  "pinterest.pt"
  "pinterest.se"
  "pixeldrain.com"
  "pixelqi.com"
  "pixiv.net"
  "pixiv.org"
  "pixivsketch.net"
  "pixnet.net"
  "pki.goog"
  "pkqjiasu.com"
  "pkuanvil.com"
  "placemix.com"
  "play-asia.com"
  "playboy.com"
  "playboyplus.com"
  "player.fm"
  "playno1.com"
  "playpcesor.com"
  "plexvpn.pro"
  "plurk.com"
  "plus.codes"
  "pmatehunter.com"
  "po2b.com"
  "podbean.com"
  "podcast.co"
  "podictionary.com"
  "podwise.ai"
  "poe.com"
  "points-media.com"
  "pokerstars.com"
  "pokerstars.net"
  "politicalchina.org"
  "poloniex.com"
  "polymarket.com"
  "polymer-project.org"
  "polymerhk.com"
  "poolbinance.com"
  "poolin.com"
  "popai.pro"
  "popvote.hk"
  "popxi.click"
  "popyard.org"
  "pornhd.com"
  "pornhub.com"
  "pornmate.com"
  "pornrapidshare.com"
  "pornstarbyface.com"
  "pornstarclub.com"
  "porntvblog.com"
  "poskotanews.com"
  "post76.com"
  "post852.com"
  "posts.careerengine.us"
  "potato.im"
  "potatso.com"
  "potvpn.com"
  "pourquoi.tw"
  "power.com"
  "powerapple.com"
  "powercx.com"
  "ppy.sh"
  "prayforchina.net"
  "prcleader.org"
  "premproxy.com"
  "presentation.new"
  "presentationzen.com"
  "president.ir"
  "presidentlee.tw"
  "prestige-av.com"
  "primevideo.com"
  "prism-break.org"
  "pritunl.com"
  "privacybox.de"
  "privacyguides.org"
  "private.com"
  "privateinternetaccess.com"
  "privatepaste.com"
  "privatetunnel.com"
  "privatevpn.com"
  "privoxy.org"
  "procopytips.com"
  "project-syndicate.org"
  "prompthero.com"
  "prosiben.de"
  "proton.me"
  "protonvpn.com"
  "provpnaccounts.com"
  "proxfree.com"
  "proxomitron.info"
  "proxpn.com"
  "proxynetwork.org.uk"
  "proxz.com"
  "proyectoclubes.com"
  "pscp.tv"
  "pshvpn.com"
  "psiphon.ca"
  "psiphon3.com"
  "pstatic.net"
  "pt.im"
  "ptt.cc"
  "pttgame.com"
  "ptwxz.com"
  "pubu.com.tw"
  "puffinbrowser.com"
  "pullfolio.co"
  "pure18.com"
  "pureconcepts.net"
  "puredns.org"
  "pureinsight.org"
  "purepdf.com"
  "purevpn.com"
  "purpose.nike.com"
  "pursuestar.com"
  "putty.org"
  "pximg.net"
  "python.com.tw"
  "qbittorrent.org"
  "qgirl.com.tw"
  "qi-gong.me"
  "qianbai.tw"
  "qiandao.today"
  "qianglie.com"
  "qiangwaikan.com"
  "qiangyou.org"
  "qianmo.tw"
  "qiwen.lu"
  "qoos.com"
  "qq.co.za"
  "qstatus.com"
  "qtcard.futunn.com"
  "qtcardfthk.futufin.com"
  "qtrac.eu"
  "questvisual.com"
  "quitccp.org"
  "quiz.directory"
  "quora.com"
  "quoracdn.net"
  "quote.longbridge.global"
  "qz.com"
  "r-pool.net"
  "r0.ru"
  "r10s.jp"
  "r18.com"
  "radio-canada.ca"
  "radio-en-ligne.fr"
  "radio.co"
  "radio.garden"
  "radioaustralia.net.au"
  "radiohilight.net"
  "radiojar.com"
  "radioline.co"
  "radiovaticana.org"
  "radiovncr.com"
  "radmin-vpn.com"
  "rael.org"
  "raggedbanner.com"
  "raidcall.com.tw"
  "rakuten.co.jp"
  "ramcity.com.au"
  "raphael.app"
  "rapidmoviez.com"
  "rapidvpn.com"
  "rarbgprx.org"
  "rateyourmusic.com"
  "rationalwiki.org"
  "raw.githack.com"
  "rawgit.com"
  "rawgithub.com"
  "rawstory.com"
  "rcam.target.com"
  "rcinet.ca"
  "rd.com"
  "reabble.com"
  "read01.com"
  "readingtimes.com.tw"
  "readmoo.com"
  "realcourage.org"
  "realitykings.com"
  "reason.com"
  "recordedfuture.com"
  "recoveryversion.com.tw"
  "red-lang.org"
  "redbubble.com"
  "redchinacn.net"
  "redd.it"
  "reddit.com"
  "reddithelp.com"
  "redditmedia.com"
  "redditspace.com"
  "redditstatic.com"
  "redhotlabs.com"
  "referer.us"
  "reflectivecode.com"
  "relay.firefox.com"
  "religionnews.com"
  "renminbao.com"
  "rentry.co"
  "renyurenquan.org"
  "resilio.com"
  "resistchina.org"
  "restofworld.org"
  "retweetrank.com"
  "reuters.com"
  "reutersmedia.net"
  "rfa.org"
  "rferl.org"
  "rfi.fr"
  "rfi.my"
  "riku.me"
  "ritter.vg"
  "rixcloud.com"
  "rixcloud.us"
  "rlwlw.com"
  "rmbl.ws"
  "roblox.com"
  "robustnessiskey.com"
  "rocket-inc.net"
  "rocket.chat"
  "rocksdb.org"
  "rojo.com"
  "rolfoundation.org"
  "rolia.net"
  "rolsociety.org"
  "ronjoneswriter.com"
  "rou.video"
  "rsdlmonitor.com"
  "rsf-chinese.org"
  "rsf.org"
  "rsshub.app"
  "rssmeme.com"
  "rtalabel.org"
  "rthk.hk"
  "rthk.org.hk"
  "rti.org.tw"
  "rti.tw"
  "rtm.tnt-ea.com"
  "rts.ch"
  "rule34.us"
  "rule34.xxx"
  "rule34video.com"
  "rumble.com"
  "rustdesk.com"
  "rusvpn.com"
  "ruten.com.tw"
  "rutracker.net"
  "rutracker.org"
  "s-cute.com"
  "s.yimg.com"
  "s3-ap-northeast-1.amazonaws.com"
  "sacks.com"
  "sacom.hk"
  "sadistic-v.com"
  "sadpanda.us"
  "safechat.com"
  "safeguarddefenders.com"
  "safervpn.com"
  "sagernet.org"
  "sakuralive.com"
  "salvation.org.hk"
  "sankakucomplex.com"
  "sankei.com"
  "sanmin.com.tw"
  "savethedate.foo"
  "savethesounds.info"
  "savetibet.de"
  "savetibet.org"
  "savetibetstore.org"
  "saveuighur.org"
  "sbti.unun.dev"
  "schema.org"
  "schwab.co.uk"
  "schwab.com"
  "schwab.com.cn"
  "schwab.com.hk"
  "scmp.com"
  "scramble.io"
  "scratch.mit.edu"
  "scribd.com"
  "scriptspot.com"
  "search.aol.com"
  "search.com"
  "search.yahoo.co.jp"
  "searx.me"
  "seattlefdc.com"
  "secretchina.com"
  "secretgarden.no"
  "secretsline.biz"
  "secure.logmein.com"
  "secure.shadowsocks.nu"
  "secureservercdn.net"
  "securetunnel.com"
  "securitykiss.com"
  "seed4.me"
  "seevpn.com"
  "seezone.net"
  "sehuatang.net"
  "sehuatang.org"
  "sensortower.com"
  "sesawe.net"
  "sethwklein.net"
  "setn.com"
  "sevenload.com"
  "sex.com"
  "sex3.com"
  "sex8.cc"
  "sexinsex.net"
  "sfshibao.com"
  "sftuk.org"
  "sgqt0j.launches.appsflyersdk.com"
  "shadeyouvpn.com"
  "shadowsocks.be"
  "shadowsocks.com.hk"
  "shadowsocks.org"
  "shahit.biz"
  "share-videos.se"
  "share.america.gov"
  "sharecool.org"
  "shattered.io"
  "sheet.new"
  "sheets.new"
  "shellfire.de"
  "shenyunperformingarts.org"
  "shenyunshop.com"
  "shenzhoufilm.com"
  "shenzhouzhengdao.org"
  "shiksha.com"
  "shitjournal.org"
  "shixiao.org"
  "shizhao.org"
  "shodanhq.com"
  "shooshtime.com"
  "shopee.tw"
  "shopping.yahoo.co.jp"
  "shortconn.im.qcloud.com"
  "showwe.tw"
  "shutterstock.com"
  "shwchurch.org"
  "sidelinesnews.com"
  "sider.ai"
  "signal.org"
  "silvergatebank.com"
  "simbolostwitter.com"
  "simianx.ai"
  "simplecd.me"
  "simplecd.org"
  "simpleswap.io"
  "simplex.chat"
  "sina.com.hk"
  "sinchew.com.my"
  "singaporepools.com.sg"
  "singlelogin.se"
  "singtao.com"
  "singtaousa.com"
  "sinoants.com"
  "sinoca.com"
  "sinocast.com"
  "sinoinsider.com"
  "sinyalee.com"
  "sis001.com"
  "site.new"
  "sitekreator.com"
  "sitemaps.org"
  "sites.new"
  "six-degrees.io"
  "sketchappsources.com"
  "skimtube.com"
  "skybet.com"
  "skyvegas.com"
  "skyxvpn.com"
  "slacker.com"
  "slashine.onl"
  "sleazyfork.org"
  "slheng.com"
  "slickvpn.com"
  "slides.com"
  "slides.new"
  "slideshare.net"
  "slutmoonbeam.com"
  "sm-miracle.com"
  "smartdnsproxy.com"
  "smh.com.au"
  "smn.news"
  "snapseed.com"
  "sndcdn.com"
  "sobees.com"
  "soc.mil"
  "social.datalabour.com"
  "social.edu.ci"
  "socialblade.com"
  "socks-proxy.net"
  "sockslist.net"
  "softether.co.jp"
  "softether.org"
  "softfamous.com"
  "softwarebychuck.com"
  "sogclub.com"
  "sogrady.me"
  "soh.tw"
  "sohcradio.com"
  "sohfrance.org"
  "solana.com"
  "solarsystem.nasa.gov"
  "solscan.io"
  "solv.finance"
  "somee.com"
  "songjianjun.com"
  "sora.com"
  "sorting-algorithms.com"
  "sos.org"
  "sosad.fun"
  "sosreader.com"
  "sotwe.com"
  "soulcaliburhentai.net"
  "soundcloud.com"
  "soundofhope.org"
  "soundon.fm"
  "soup.io"
  "south-plus.net"
  "south-plus.org"
  "southmongolia.org"
  "southnews.com.tw"
  "southpark.cc.com"
  "sowers.org.hk"
  "spaceforce.mil"
  "spaces.hightail.com"
  "spacex.com"
  "spankbang.com"
  "sparkpool.com"
  "spatial.io"
  "spb.com"
  "speakerdeck.com"
  "speedcat.me"
  "speedify.com"
  "spencertipping.com"
  "spendee.com"
  "spicevpn.com"
  "spideroak.com"
  "spiderpool.com"
  "sports.williamhill.com"
  "spotflux.com"
  "spotify.com"
  "spreadsheet.new"
  "spreadshirt.es"
  "spreaker.com"
  "spring4u.info"
  "springboardplatform.com"
  "springwood.me"
  "sproutcore.com"
  "squirrelvpn.com"
  "ss-link.com"
  "ssl.webpack.de"
  "sspanel.net"
  "ssr.tools"
  "ssrshare.com"
  "ssrshare.us"
  "ssrtool.com"
  "sstm.moe"
  "sstmlt.moe"
  "sstmlt.net"
  "standard.co.uk"
  "standupfortibet.org"
  "standwithhk.org"
  "starp2p.com"
  "startpage.com"
  "static-economist.com"
  "static.pocketcasts.com"
  "static.shemalez.com"
  "staticflickr.com"
  "stboy.net"
  "stc.com.sa"
  "steamcommunity.com"
  "steamladder.com"
  "steamstatic.com"
  "steel-storm.com"
  "steemit.com"
  "steganos.com"
  "stephaniered.com"
  "sthoo.com"
  "stitcher.com"
  "stoptibetcrisis.net"
  "storage.yandex.net"
  "storagenewsletter.com"
  "store.steampowered.com"
  "storj.io"
  "storm.mg"
  "storry.tv"
  "stoweboyd.com"
  "straitstimes.com"
  "straplessdildo.com"
  "streamable.com"
  "streamate.com"
  "streamingthe.net"
  "strongvpn.com"
  "studentsforafreetibet.org"
  "stumbleupon.com"
  "subhd.tv"
  "substack.com"
  "suche.gmx.net"
  "sugarsync.com"
  "sugumiru18.com"
  "suissl.com"
  "sujiatun.wordpress.com"
  "sumrando.com"
  "sundayguardianlive.com"
  "sunmedia.ca"
  "suno.ai"
  "suno.com"
  "sunporno.com"
  "supchina.com"
  "superpages.com"
  "supervpn.net"
  "support.futunn.com"
  "supremecourt.gov"
  "surfeasy.com"
  "surfshark.com"
  "surrenderat20.net"
  "suyingtv.com"
  "swagbucks.com"
  "swapspace.co"
  "swissinfo.ch"
  "swissvpn.net"
  "switch1.jp"
  "switchvpn.net"
  "sydney.bing.com"
  "sydneytoday.com"
  "sylfoundation.org"
  "synapse.org"
  "syncback.com"
  "synergyse.com"
  "syosetu.com"
  "t-g.com"
  "t.co"
  "t.me"
  "t66y.com"
  "taaze.tw"
  "taedp.org.tw"
  "tagwalk.com"
  "tails.net"
  "taipeisociety.org"
  "taipeitimes.com"
  "taisounds.com"
  "taiwanhot.net"
  "taiwanjustice.net"
  "taiwanncf.org.tw"
  "taiwannews.com.tw"
  "taiwantt.org.tw"
  "talkatone.com"
  "talkboxapp.com"
  "talkcc.com"
  "talkonly.net"
  "tanc.org"
  "tanks.gg"
  "tap.io"
  "tapanwap.com"
  "tapatalk.com"
  "taptap.io"
  "tardigrade.io"
  "taup.net"
  "taweet.com"
  "tbcollege.org"
  "tbsec.org"
  "tbsn.org"
  "teachparentstech.org"
  "techbang.com"
  "technews.tw"
  "techviz.net"
  "teck.in"
  "teco-hk.org"
  "teco-mo.org"
  "teddysun.com"
  "tehrantimes.com"
  "telega.one"
  "telegra.ph"
  "telegram.dog"
  "telegram.me"
  "telegram.org"
  "telegram.space"
  "telegramdownload.com"
  "telesco.pe"
  "tellapart.com"
  "temu.com"
  "tenor.com"
  "tensorflow.org"
  "tenzinpalmo.com"
  "terabox.com"
  "terobox.com"
  "tew.org"
  "textnow.com"
  "textnow.me"
  "tfc-taiwan.org.tw"
  "tfhub.dev"
  "tfiflve.com"
  "tg-me.com"
  "tg.dev"
  "tgstat.com"
  "the-sun.com"
  "theatlantic.com"
  "theatrum-belli.com"
  "thebcomplex.com"
  "theblaze.com"
  "thebobs.com"
  "thebodyshop-usa.com"
  "thecenter.mit.edu"
  "thechasernews.co.uk"
  "thechinacollection.org"
  "theconversation.com"
  "thediplomat.com"
  "thedw.us"
  "theepochtimes.com"
  "thefacebook.com"
  "thegay.com"
  "theguardian.com"
  "thehansindia.com"
  "thehindu.com"
  "thehun.net"
  "theinitium.com"
  "theintercept.com"
  "thenewslens.com"
  "thepiratebay.org"
  "theporndude.com"
  "theportalwiki.com"
  "theprint.in"
  "thesaturdaypaper.com.au"
  "thestandnews.com"
  "thetatoken.org"
  "thetibetpost.com"
  "thetvdb.com"
  "theweek.com"
  "thewgo.org"
  "thewirechina.com"
  "thinkchina.sg"
  "thinkgeek.com"
  "thinkingtaiwan.com"
  "thinkwithgoogle.com"
  "thirdmill.org"
  "thisav.com"
  "thomasbernhard.org"
  "threadreaderapp.com"
  "threads.com"
  "threads.net"
  "throughnightsfire.com"
  "thuhole.com"
  "thywords.com"
  "tiananmenduizhi.com"
  "tiananmenuniv.com"
  "tiananmenuniv.net"
  "tiandixing.org"
  "tianti.io"
  "tiantibooks.org"
  "tibet-envoy.eu"
  "tibet-initiative.de"
  "tibet.com"
  "tibet.net"
  "tibet.nu"
  "tibet.org"
  "tibet.org.tw"
  "tibet.to"
  "tibetaction.net"
  "tibetanbuddhistinstitute.org"
  "tibetancommunity.org"
  "tibetanentrepreneurs.org"
  "tibetanhealth.org"
  "tibetanliberation.org"
  "tibetanyouthcongress.org"
  "tibetcorps.org"
  "tibetexpress.net"
  "tibetfocus.com"
  "tibetfund.org"
  "tibetgermany.de"
  "tibethouse.jp"
  "tibethouse.org"
  "tibethouse.us"
  "tibetmuseum.org"
  "tibetnetwork.org"
  "tibetoffice.ch"
  "tibetoffice.com.au"
  "tibetoffice.org"
  "tibetonline.com"
  "tibetonline.tv"
  "tibetoralhistory.org"
  "tibetpolicy.eu"
  "tibetrelieffund.co.uk"
  "tibetsociety.com"
  "tibetsun.com"
  "tibetsupportgroup.org"
  "tibetswiss.ch"
  "tibettelegraph.com"
  "tibettimes.net"
  "tibettruth.com"
  "tibetwrites.org"
  "tigerbbs.cn"
  "tigerbbs.com"
  "tigerbrokers.com"
  "tigerbrokers.net"
  "tigerbrokers.nz"
  "tigerfintech.com"
  "tigervpn.com"
  "tiktok.com"
  "tiktokcdn-eu.com"
  "tiktokcdn-us.com"
  "tiktokcdn.com"
  "tiktokv.com"
  "tiktokv.us"
  "tiltbrush.com"
  "time.com"
  "timesnownews.com"
  "timesofindia.indiatimes.com"
  "timtales.com"
  "tinc-vpn.org"
  "tineye.com"
  "tingtalk.me"
  "tiny.cc"
  "tinychat.com"
  "tinypaste.com"
  "tinyurl.com"
  "tipas.net"
  "tkcs-collins.com"
  "tma.co.jp"
  "tmagazine.com"
  "tn1.shemalez.com"
  "tn2.shemalez.com"
  "tn3.shemalez.com"
  "tnaflix.com"
  "to-porno.com"
  "togetter.com"
  "token.im"
  "tokenlon.im"
  "tokyo-porn-tube.com"
  "tokyocn.com"
  "tomp3.cc"
  "top.tv"
  "top10vpn.com"
  "topbtc.com"
  "topsy.com"
  "toptip.ca"
  "toptoon.net"
  "tor.eff.org"
  "torguard.net"
  "torlock.com"
  "torproject.org"
  "torrentgalaxy.to"
  "torrentkitty.tv"
  "torrentprivacy.com"
  "torrenty.org"
  "tortoisesvn.net"
  "torvpn.com"
  "totalvpn.com"
  "tou.tv"
  "tpi.org.tw"
  "tracfone.com"
  "trade.futunn.com"
  "trade.longportapp.com"
  "tradeup.com"
  "tradingview.com"
  "translate.goog"
  "transparency.org"
  "treemall.com.tw"
  "trendsmap.com"
  "tronscan.org"
  "trouw.nl"
  "trt.net.tr"
  "trtworld.com"
  "truebuddha-md.org"
  "trustwallet.com"
  "truthsocial.com"
  "tryheart.jp"
  "tsdr.uspto.gov"
  "tt1069.com"
  "tttan.com"
  "ttv.com.tw"
  "ttvnw.net"
  "tube8.com"
  "tube911.com"
  "tubepornclassic.com"
  "tubewolf.com"
  "tuidang.org"
  "tukaani.org"
  "tumblr.com"
  "tumview.com"
  "tunein.streamguys1.com"
  "tunnelbear.com"
  "tunnelblick.net"
  "tunnelr.com"
  "tunsafe.com"
  "turbobit.net"
  "turbohide.com"
  "turkistantimes.com"
  "turntable.fm"
  "tuvpn.com"
  "tv.jtbc.joins.com"
  "tvbanywhere.com"
  "tvboxnow.com"
  "tvdy1.com"
  "tvunetworks.com"
  "tw.jiepang.com"
  "twapperkeeper.com"
  "twaud.io"
  "twblogger.com"
  "tweepguide.com"
  "tweepml.org"
  "tweetbackup.com"
  "tweetboard.com"
  "tweetdeck.com"
  "tweetedtimes.com"
  "tweetphoto.com"
  "tweetree.com"
  "tweettunnel.com"
  "tweetwally.com"
  "twelve.today"
  "twerkingbutt.com"
  "twftp.org"
  "twgov.tw"
  "twgreatdaily.com"
  "twibble.de"
  "twibs.com"
  "twiffo.com"
  "twiggit.org"
  "twimg.com"
  "twip.me"
  "twipple.jp"
  "twishort.com"
  "twister.net.co"
  "twitch.tv"
  "twitchcdn.net"
  "twitiq.com"
  "twitlonger.com"
  "twitoaster.com"
  "twitonmsn.com"
  "twitpic.com"
  "twitstat.com"
  "twitter.com"
  "twitter.jp"
  "twitter4j.org"
  "twittercounter.com"
  "twittergadget.com"
  "twitterkr.com"
  "twittermail.com"
  "twitterrific.com"
  "twittertim.es"
  "twitturk.com"
  "twitturly.com"
  "twkan.com"
  "twreporter.org"
  "twstalker.com"
  "twttr.com"
  "tx.me"
  "tycool.com"
  "typepad.com"
  "typeset.io"
  "typora.io"
  "u15.info"
  "u9un.com"
  "ua5v.com"
  "uberproxy.net"
  "uc-japan.org"
  "udn.com"
  "udn.com.tw"
  "udomain.hk"
  "uforadio.com.tw"
  "uhdwallpapers.org"
  "uhrp.org"
  "uighur.nl"
  "uku.im"
  "ulop.net"
  "ultrasurf.us"
  "ultravpn.com"
  "ultravpn.fr"
  "umap.openstreetmap.fr"
  "unblock-us.com"
  "unblock.cn.com"
  "unblocksit.es"
  "underwoodammo.com"
  "unholyknight.com"
  "unirule.cloud"
  "uniswap.org"
  "unknownspace.org"
  "unmineable.com"
  "unseen.is"
  "unstable.icu"
  "unwire.hk"
  "uocn.org"
  "up.audio"
  "upbit.com"
  "updates.tdesktop.com"
  "upghsbc.com"
  "upmedia.mg"
  "uproxy.org"
  "upsangel.com"
  "uptodown.com"
  "uraban.me"
  "urbandictionary.com"
  "urbansurvival.com"
  "urchin.com"
  "urlborg.com"
  "urlparser.com"
  "usacn.com"
  "usaip.eu"
  "uscardforum.com"
  "uscg.mil"
  "uscnpm.org"
  "use.typekit.net"
  "usercontent.goog"
  "usfk.mil"
  "usma.edu"
  "usno.navy.mil"
  "ustibetcommittee.org"
  "ustream.tv"
  "utopianpal.com"
  "uujiasu.com"
  "uukanshu.com"
  "uupool.cn"
  "uvwxyz.xyz"
  "uwants.com"
  "uyghur-j.org"
  "uyghuraa.org"
  "uyghuramerican.org"
  "uyghurbiz.org"
  "uyghurcongress.org"
  "uyghurpen.org"
  "uyghurstudies.org"
  "uyghurtribunal.com"
  "v2.help"
  "v2.hysteria.network"
  "v2ex.com"
  "v2fly.org"
  "v2ray.com"
  "v2raycn.com"
  "valeursactuelles.com"
  "vansky.com"
  "vaticannews.va"
  "vatn.org"
  "vcf-online.org"
  "vcfbuilder.org"
  "veed.io"
  "vegas.williamhill.com"
  "vegasred.com"
  "venetianmacao.com"
  "ventureswell.com"
  "vercel.app"
  "vern.cc"
  "verybs.com"
  "vevo.com"
  "vewas.net"
  "viber.com"
  "victimsofcommunism.org"
  "vid.me"
  "vidble.com"
  "video.aol.com"
  "videobam.com"
  "videomega.tv"
  "videopress.com"
  "vilanet.me"
  "vilavpn.com"
  "vimeo.com"
  "vimeocdn.com"
  "vimperator.org"
  "vincnd.com"
  "vine.co"
  "vinniev.com"
  "vip-enterprise.com"
  "virtualrealporn.com"
  "viu.com"
  "vivaldi.com"
  "vivthomas.com"
  "vjav.com"
  "vmixcore.com"
  "vmpsoft.com"
  "vnet.link"
  "voacambodia.com"
  "voacantonese.com"
  "voachinese.com"
  "voachineseblog.com"
  "voaindonesia.com"
  "voanews.com"
  "voatibetan.com"
  "voatibetanenglish.com"
  "vocaroo.com"
  "vocus.cc"
  "vod-abematv.akamaized.net"
  "vod.wwe.com"
  "voicettank.org"
  "vot.org"
  "vox.com"
  "voxer.com"
  "vpl.bibliocommons.com"
  "vpn.ac"
  "vpn.net"
  "vpn4all.com"
  "vpnaccounts.com"
  "vpncup.com"
  "vpndada.com"
  "vpnforgame.net"
  "vpngate.jp"
  "vpngate.net"
  "vpnhub.com"
  "vpninja.net"
  "vpnjack.com"
  "vpnmaster.com"
  "vpnmentor.com"
  "vpnpick.com"
  "vpnpop.com"
  "vpnpronet.com"
  "vpnproxymaster.com"
  "vpnreactor.com"
  "vpnreviewz.com"
  "vpnsecure.me"
  "vpnshazam.com"
  "vpnshieldapp.com"
  "vpntunnel.com"
  "vpnuk.info"
  "vpnunlimitedapp.com"
  "vpnvip.com"
  "vporn.com"
  "vpsxb.net"
  "vrchat.com"
  "vrporn.com"
  "vrsmash.com"
  "vtunnel.com"
  "vultryhw.com"
  "w-pool.com"
  "waffle1999.com"
  "wainao.me"
  "walletconnect.com"
  "walletconnect.org"
  "wallmama.com"
  "wallpapercasa.com"
  "wallsttv.com"
  "wallzhihu.com"
  "waltermartin.com"
  "waltermartin.org"
  "wanderinghorse.net"
  "wangafu.net"
  "wangjinbo.org"
  "wango.org"
  "want-daily.com"
  "wanz-factory.com"
  "warroom.org"
  "waselpro.com"
  "washingtonpost.com"
  "washingtontimes.com"
  "watchinese.com"
  "watchmygf.net"
  "watchout.tw"
  "wattpad.com"
  "wav.tv"
  "waveprotocol.org"
  "waybig.com"
  "waymo.com"
  "wbrks.com"
  "wd.bible"
  "wealth.com.tw"
  "wearn.com"
  "web.dev"
  "web2project.net"
  "webmproject.org"
  "webpkgcache.com"
  "webrtc.org"
  "websdr.org"
  "webshare.io"
  "website.new"
  "wechatlawsuit.com"
  "weebly.com"
  "wefightcensorship.org"
  "wego.here.com"
  "weights.com"
  "weijingsheng.org"
  "weiming.info"
  "welt.de"
  "wengewang.org"
  "wenxuecity.com"
  "wenyunchao.com"
  "wenzhao.ca"
  "westca.com"
  "westernwolves.com"
  "westpoint.edu"
  "wezone.net"
  "wforum.com"
  "whatblocked.com"
  "whatbrowser.org"
  "whats.new"
  "whatsapp.com"
  "whatsapp.net"
  "whatsonweibo.com"
  "wheelockslatin.com"
  "whereiswerner.com"
  "wheretowatch.com"
  "whispersystems.org"
  "whoer.net"
  "whyx.org"
  "widevine.com"
  "wiki.jqueryui.com"
  "wiki.metacubex.one"
  "wiki.oauth.net"
  "wiki.phonegap.com"
  "wikibooks.org"
  "wikidata.org"
  "wikileaks.ch"
  "wikileaks.com"
  "wikileaks.de"
  "wikileaks.eu"
  "wikileaks.lu"
  "wikileaks.org"
  "wikileaks.pl"
  "wikiless.funami.tech"
  "wikimapia.org"
  "wikimedia.org"
  "wikinews.org"
  "wikipedia.com"
  "wikipedia.org"
  "wikis.tw"
  "wikisource.org"
  "wikiunblocked.org"
  "wikiversity.org"
  "wikivoyage.org"
  "wikiwand.com"
  "wiktionary.org"
  "willw.net"
  "wilsoncenter.org"
  "windscribe.com"
  "wingamestore.com"
  "wingy.site"
  "wionews.com"
  "wire.com"
  "wiredbytes.com"
  "wiredpen.com"
  "wireguard.com"
  "wisevid.com"
  "wispbyte.com"
  "withgoogle.com"
  "withyoutube.com"
  "witopia.net"
  "wizcrafts.net"
  "wjbk.org"
  "wmflabs.org"
  "wmfusercontent.org"
  "wn.com"
  "wnacg.com"
  "wnacg.org"
  "wo.tc"
  "wo3ttt.wordpress.com"
  "woeser.com"
  "wokar.org"
  "wolfax.com"
  "wombo.ai"
  "woolyss.com"
  "woopie.jp"
  "woopie.tv"
  "work2icu.org"
  "workatruna.com"
  "workerempowerment.org"
  "workers.dev"
  "worldjournal.com"
  "worldvpn.net"
  "wowgirls.com"
  "wowhead.com"
  "wowporn.com"
  "wp.com"
  "wplace.live"
  "wpoforum.com"
  "writesonic.com"
  "wsj.com"
  "wsj.net"
  "wufafangwen.com"
  "wufi.org.tw"
  "wujieliulan.com"
  "wunderground.com"
  "wuw.red"
  "wwitv.com"
  "www.ajsands.com"
  "www.bing.com"
  "www.clashverge.dev"
  "www.hoyolab.com"
  "www.lorenzetti.com.br"
  "www.moztw.org"
  "www.msn.com"
  "www.powerpointninja.com"
  "www.shadowsocks.com"
  "www.wan-press.org"
  "www.xicons.org"
  "wxw.cat"
  "wxw.moe"
  "x-art.com"
  "x-berry.com"
  "x-wall.org"
  "x.ai"
  "x.co"
  "x.com"
  "x.company"
  "x3guide.com"
  "xbabe.com"
  "xbookcn.com"
  "xbtce.com"
  "xcafe.in"
  "xcancel.com"
  "xcity.jp"
  "xdaforums.com"
  "xerotica.com"
  "xfinity.com"
  "xfxssr.me"
  "xgmyd.com"
  "xhamster.com"
  "xiaohexie.com"
  "xiaohu8.com"
  "xiaolan.me"
  "xiaoma.org"
  "xiaomi.eu"
  "xiaxiaoqiang.net"
  "xijie.wordpress.com"
  "xinjiangpolicefiles.org"
  "xinmiao.com.hk"
  "xjtravelguide.com"
  "xm.com"
  "xml-training-guide.com"
  "xn--11xs86f.icu"
  "xn--1jqvh729avzfcy2d8ummib.com"
  "xn--4gq171p.com"
  "xn--9iqy04a7fi01l.com"
  "xn--9pr62r24a.com"
  "xn--czq75pvv1aj5c.org"
  "xn--i2ru8q2qg.com"
  "xn--kcrv3utim32hx9f6qe.com"
  "xn--ngstr-lra8j.com"
  "xn--noss43i.com"
  "xn--oiq.cc"
  "xn--p8j9a0d9c9a.xn--q9jyb4c"
  "xn--u2u927b.com"
  "xn--vuqv2cf7wzyig79c.com"
  "xnpool.com"
  "xnxx.com"
  "xpud.org"
  "xsden.info"
  "xskywalker.com"
  "xt.com"
  "xt.pub"
  "xtube.com"
  "xuan.com.my"
  "xuchao.net"
  "xuchao.org"
  "xuehua.us"
  "xvbelink.com"
  "xvideos-cdn.com"
  "xvideos.com"
  "xvideos.es"
  "xvinlink.com"
  "xxx.com"
  "xxxx.com.au"
  "y2mate.com"
  "yadi.sk"
  "yahoo.com"
  "yahoo.com.hk"
  "yahoo.com.tw"
  "yakbutterblues.com"
  "yam.com"
  "yam.org.tw"
  "yande.re"
  "yangzhi.org"
  "yasni.co.uk"
  "yasukuni.or.jp"
  "yeahteentube.com"
  "yecl.net"
  "yeelou.com"
  "yeeyi.com"
  "yegle.net"
  "yes-news.com"
  "yes123.com.tw"
  "yesasia.com"
  "yesasia.com.hk"
  "yespornplease.com"
  "yfsp.tv"
  "yhcw.net"
  "yibaochina.com"
  "yigeni.com"
  "yipub.com"
  "yizhihongxing.com"
  "yobit.net"
  "yobt.tv"
  "yogichen.org"
  "you-get.org"
  "you.com"
  "youjizz.com"
  "youmaker.com"
  "youmind.com"
  "youpai.org"
  "youporn.com"
  "youporngay.com"
  "yourepeat.com"
  "yourlisten.com"
  "yourlust.com"
  "yousendit.com"
  "youtu.be"
  "youtube-nocookie.com"
  "youtube.com"
  "youtubeeducation.com"
  "youtubegaming.com"
  "youtubekids.com"
  "youversion.com"
  "youwin.com"
  "youxu.info"
  "yt.be"
  "ytimg.com"
  "ytn.co.kr"
  "yulghun.com"
  "yunchao.net"
  "yunomi.tokyo"
  "yvesgeleyn.com"
  "yyii.org"
  "yyjlymb.xyz"
  "yysub.net"
  "yzzk.com"
  "z-lib.fm"
  "z-lib.fo"
  "z-lib.gd"
  "z-lib.gl"
  "z-lib.io"
  "z-lib.org"
  "z-library.ec"
  "z-library.sk"
  "zalmos.com"
  "zamimg.com"
  "zaochenbao.com"
  "zattoo.com"
  "zb.com"
  "zdnet.com.tw"
  "zello.com"
  "zenmate.com"
  "zenmate.com.ru"
  "zerohedge.com"
  "zeronet.io"
  "zh-hans.cfsh99.com"
  "zh.ecdm.wikia.com"
  "zh.pokerstrategy.com"
  "zh.wikiquote.org"
  "zhangtianliang.com"
  "zhangzhehan.net"
  "zhanlve.org"
  "zhao.1984.city"
  "zhengjian.org"
  "zhengwunet.org"
  "zhijianfengyi.cn"
  "zhijianfengyi.com"
  "zhizhu.top"
  "zhongguotese.net"
  "zhongzidi.com"
  "zhuatieba.com"
  "zhuichaguoji.org"
  "zi.media"
  "zillionk.com"
  "zim.vn"
  "zinio.com"
  "zmedia.com.tw"
  "zmw.cn"
  "zodgame.xyz"
  "zonaeuropa.com"
  "zonghexinwen.com"
  "zoogvpn.com"
  "zoominfo.com"
  "zooqle.com"
  "zootool.com"
  "zophar.net"
  "zorrovpn.com"
  "zozotown.com"
  "zpn.im"
  "zspeeder.me"
  "zuo.la"
  "zuobiao.me"
  "zuola.com"
  "zvereff.com"
  "zynamics.com"
  "zyxel.com"
  "zzcloud.me"
)

host_sni_risk() {
  local host="${1,,}" suffix
  host="${host%.}"
  for suffix in "${GFWLIST_SUFFIXES[@]}"; do
    [[ "$host" == "$suffix" || "$host" == *."$suffix" ]] && { echo gfwlist; return 0; }
  done
  return 1
}

REGION_KEYS=(global us eu jp hk sg cn au kr)
region_label() {
  case "$1" in
    global) echo "全球通用(大厂CDN)" ;;
    us)     echo "美国/北美" ;;
    eu)     echo "欧洲" ;;
    jp)     echo "日本" ;;
    hk)     echo "香港" ;;
    sg)     echo "东南亚/新加坡" ;;
    cn)     echo "中国大陆" ;;
    au)     echo "澳洲" ;;
    kr)     echo "韩国" ;;
    *)      echo "$1" ;;
  esac
}

# 全部站点去重
all_hosts() { local k; for k in "${CAT_KEYS[@]}"; do cat_hosts "$k"; done | awk '!seen[$0]++'; }

# 某地区的候选：该区归属站 + 全球站（global 永远纳入，作为安全底牌）
region_hosts() {
  local r="$1" h reg
  all_hosts | while IFS= read -r h; do
    [[ -z "$h" ]] && continue
    reg=$(host_region "$h")
    if [[ "$r" == "global" ]]; then
      [[ "$reg" == "global" ]] && echo "$h"
    else
      [[ "$reg" == "$r" || "$reg" == "global" ]] && echo "$h"
    fi
  done
}

ROUNDS=3          # 每站探测次数，取最小值避免抖动
TIMEOUT=5         # 单次连接超时(秒)
EXTRA_HOSTS=()
INTERACTIVE_ONLY=0
SEL_CATS=()       # -c 指定的分类；空=全部
SEL_REGION=""     # -r 指定的地区；空=不按地区

# ---------------- 颜色 ----------------
if [[ -t 1 ]]; then
  C_B=$'\e[1m'; C_G=$'\e[32m'; C_Y=$'\e[33m'; C_R=$'\e[31m'; C_D=$'\e[2m'; C_C=$'\e[36m'; NC=$'\e[0m'
else
  C_B=""; C_G=""; C_Y=""; C_R=""; C_D=""; C_C=""; NC=""
fi

usage() { grep '^#' "$0" | sed '/^#!/d; s/^# \{0,1\}//' | head -22; exit 0; }

die() {
  printf "%s错误: %s%s\n" "$C_R" "$*" "$NC" >&2
  exit 1
}

is_positive_int() {
  [[ "$1" =~ ^[1-9][0-9]*$ ]]
}

category_exists() {
  local want="$1" k
  for k in "${CAT_KEYS[@]}"; do
    [[ "$k" == "$want" ]] && return 0
  done
  return 1
}

region_exists() {
  local want="$1" r
  for r in "${REGION_KEYS[@]}"; do
    [[ "$r" == "$want" ]] && return 0
  done
  return 1
}

validate_options() {
  local k
  is_positive_int "$ROUNDS" || die "-n 必须是正整数: $ROUNDS"
  is_positive_int "$TIMEOUT" || die "-t 必须是正整数秒数: $TIMEOUT"
  for k in "${SEL_CATS[@]}"; do
    category_exists "$k" || die "未知分类: $k"
  done
  if [[ -n "$SEL_REGION" ]]; then
    region_exists "$SEL_REGION" || die "未知地区: $SEL_REGION"
  fi
}

OPENSSL_X25519_ARGS=()
detect_openssl_x25519_args() {
  local help
  help=$(openssl s_client -help 2>&1 || true)
  if grep -q -- "-groups" <<< "$help"; then
    OPENSSL_X25519_ARGS=(-groups X25519)
  elif grep -q -- "-curves" <<< "$help"; then
    OPENSSL_X25519_ARGS=(-curves X25519)
  fi
}

probe_x25519() {
  local host="$1" xs
  [[ ${#OPENSSL_X25519_ARGS[@]} -gt 0 ]] || return 1
  xs=$(echo -n | timeout "$TIMEOUT" openssl s_client -connect "${host}:443" \
        -servername "$host" -verify_hostname "$host" -alpn h2,http/1.1 \
        "${OPENSSL_X25519_ARGS[@]}" 2>&1 | tr -d '\0')
  grep -qE "New, TLSv1\.3|Protocol *: *TLSv1\.3" <<< "$xs" || return 1
  grep -qiE "Verify return code: 0 \(ok\)|Verification: OK" <<< "$xs" || return 1
  return 0
}

list_cats() {
  printf "${C_B}可用分类 (用 -c 选，逗号分隔):${NC}\n"
  for k in "${CAT_KEYS[@]}"; do
    printf "  ${C_C}%-8s${NC} %s  ${C_D}(%d 站)${NC}\n" "$k" "$(cat_label "$k")" "$(cat_hosts "$k" | grep -c .)"
  done
  exit 0
}

while getopts "a:c:r:n:t:ilh" opt; do
  case "$opt" in
    a) read -r -a EXTRA_HOSTS <<< "$OPTARG" ;;
    c) IFS=', ' read -r -a SEL_CATS <<< "$OPTARG" ;;
    r) SEL_REGION="$OPTARG" ;;
    n) ROUNDS="$OPTARG" ;;
    t) TIMEOUT="$OPTARG" ;;
    i) INTERACTIVE_ONLY=1 ;;
    l) list_cats ;;
    h) usage ;;
    *) usage ;;
  esac
done

validate_options
detect_openssl_x25519_args

# 环境变量覆盖：SNI_HOSTS 优先级最高，直接替换全部内置分类
SNI_OVERRIDE=()
[[ -n "${SNI_HOSTS:-}" ]] && read -r -a SNI_OVERRIDE <<< "$SNI_HOSTS"

# 把 URL / 带路径的输入规整成纯主机名
normalize_host() {
  local h="$1"
  h="${h#http://}"; h="${h#https://}"   # 去 scheme
  h="${h%%/*}"                          # 去路径
  h="${h%%:*}"                          # 去端口
  h="${h// /}"                          # 去空格
  printf '%s' "$h"
}

# 探测单个站点，输出: "minHandshake tls13 h2 tempkey chain httpcode certok"
probe_host() {
  local host="$1" best="" code="-" line ac hc

  # 详情：一次 openssl -showcerts 拿 TLS1.3 / ALPN(h2) / 临时密钥(X25519) / 证书链层数 / 证书验证结果
  local so tls13="no" h2="no" tempkey="-" chain=0 certok="no"
  so=$(echo -n | timeout "$TIMEOUT" openssl s_client -connect "${host}:443" \
        -servername "$host" -verify_hostname "$host" -alpn h2,http/1.1 \
        -showcerts 2>&1 | tr -d '\0')
  grep -qE "New, TLSv1\.3|Protocol *: *TLSv1\.3" <<< "$so" && tls13="yes"
  grep -qi "ALPN protocol: h2" <<< "$so" && h2="yes"
  grep -qiE "Verify return code: 0 \(ok\)|Verification: OK" <<< "$so" && certok="yes"
  tempkey=$(grep "Server Temp Key" <<< "$so" | sed 's/.*Server Temp Key: *//; s/,.*//' | head -1)
  [[ -z "$tempkey" ]] && tempkey="-"
  if [[ "$tls13" == "yes" && "$certok" == "yes" && "$tempkey" != *X25519* ]] && probe_x25519 "$host"; then
    tempkey="X25519"
  fi
  chain=$(grep -c "BEGIN CERTIFICATE" <<< "$so")   # 证书链层数(叶子+中间)
  [[ -z "$chain" ]] && chain=0
  local handshake_ok="no"; [[ "$chain" -ge 1 ]] && handshake_ok="yes"

  # 延迟：只测 TLS 握手(time_appconnect)——这正是 Reality 关心的、与 HTTP 层无关。
  #   用 --http1.1 避开部分站(Akamai 等)对裸 curl 的 h2 INTERNAL_ERROR；
  #   即使 HTTP 被拦(code=000/403)，握手时间仍有效，照常采用，不再误判失败。
  for _ in $(seq 1 "$ROUNDS"); do
    line=$(curl -sS -o /dev/null --http1.1 --max-time "$TIMEOUT" \
        -w "%{time_appconnect} %{http_code}" "https://${host}/" 2>/dev/null)
    ac="${line%% *}"; hc="${line##* }"
    if [[ -n "$ac" && "$ac" != "0.000000" && "$ac" != "0" ]]; then
      [[ -n "$hc" && "$hc" != "000" ]] && code="$hc"
      if [[ -z "$best" ]] || awk "BEGIN{exit !($ac < $best)}"; then best="$ac"; fi
    fi
  done

  # curl 一次握手时间都没拿到，但 openssl 握手其实成功 → 用 openssl 计时兜底
  if [[ -z "$best" && "$handshake_ok" == "yes" && "$certok" == "yes" ]]; then
    local t0 t1
    t0=$(date +%s.%N 2>/dev/null)
    echo -n | timeout "$TIMEOUT" openssl s_client -connect "${host}:443" \
         -servername "$host" -verify_hostname "$host" -verify_return_error >/dev/null 2>&1
    t1=$(date +%s.%N 2>/dev/null)
    if [[ -n "$t0" && -n "$t1" ]]; then
      best=$(awk "BEGIN{d=$t1-$t0; if(d>0)printf \"%.3f\",d; else print \"\"}")
      [[ -n "$best" ]] && code="tls"    # 标记：握手可用，HTTP 层无响应
    fi
  fi

  [[ -z "$best" ]] && { printf 'FAIL %s %s %s %s %s %s' "$tls13" "$h2" "$tempkey" "$chain" "$code" "$certok"; return; }
  printf '%s %s %s %s %s %s %s' "$best" "$tls13" "$h2" "$tempkey" "$chain" "$code" "$certok"
}

# 表头
print_header() {
  printf "\n${C_B}%-24s %10s  %-6s %-4s %-14s %-4s %-5s %s${NC}\n" \
    "SNI 站点" "握手(s)" "TLS1.3" "h2" "临时密钥" "链" "HTTP" "合规"
  printf "${C_D}%s${NC}\n" "--------------------------------------------------------------------------------------------"
}

# 单行渲染 + 收集用于排序 (host|ac|qualify)
RESULTS=()
render_row() {
  local host="$1" out ac tls13 h2 tempkey chain code certok qualify mark result_tag ac_disp x25519="no" sni_risk=""
  out=$(probe_host "$host")
  read -r ac tls13 h2 tempkey chain code certok <<< "$out"

  if [[ "$ac" == "FAIL" ]]; then
    if [[ "$tls13" == "yes" && "$certok" != "yes" ]]; then
      printf "${C_R}%-24s %10s  %-6s %-4s %-14s %-4s %-5s %s${NC}\n" \
        "$host" "证书无效" "$tls13" "$h2" "${tempkey:0:14}" "$chain" "$code" "✗ 证书"
      RESULTS+=("$host|999|no")
      return
    fi
    printf "${C_R}%-24s %10s  %-6s %-4s %-14s %-4s %-5s %s${NC}\n" \
      "$host" "超时/失败" "-" "-" "-" "-" "$code" "✗"
    RESULTS+=("$host|999|no")
    return
  fi

  [[ "$tempkey" == *X25519* ]] && x25519="yes"
  sni_risk=$(host_sni_risk "$host")
  # 证书链: 1~2 短链最优, 3 尚可, 4+ 偏长(Reality 借用握手易出问题)
  local chain_ok="no"
  [[ "$chain" =~ ^[0-9]+$ && "$chain" -ge 1 && "$chain" -le 3 ]] && chain_ok="yes"

  # Reality 合规: TLS1.3 必须; h2 / X25519 / 短证书链 三者齐 = 推荐
  if [[ "$tls13" == "yes" && "$certok" != "yes" ]]; then
    qualify="${C_R}✗ 证书${NC}"; mark="bad"; result_tag="bad"
  elif [[ "$tls13" == "yes" && -n "$sni_risk" ]]; then
    qualify="${C_Y}△ SNI风险${NC}"; mark="bad"; result_tag="risk"
  elif [[ "$tls13" == "yes" && "$h2" == "yes" && "$x25519" == "yes" && "$chain_ok" == "yes" ]]; then
    qualify="${C_G}✓ 推荐${NC}"; mark="ok"; result_tag="full"
  elif [[ "$tls13" == "yes" && "$chain" -gt 3 ]]; then
    qualify="${C_Y}△ 链偏长${NC}"; mark="ok"; result_tag="chain"      # 其它没问题但链太长，能试不首选
  elif [[ "$tls13" == "yes" ]]; then
    qualify="${C_Y}△ 可用${NC}"; mark="ok"; result_tag="partial"        # 缺 h2 或 x25519
  else
    qualify="${C_R}✗ 不可${NC}"; mark="bad"; result_tag="bad"        # 无 TLS1.3
  fi

  ac_disp=$(awk "BEGIN{printf \"%.3f\", $ac}")
  local ct ch cc
  [[ "$tls13" == "yes" ]] && ct="${C_G}yes${NC}" || ct="${C_R}no${NC}"
  [[ "$h2"   == "yes" ]] && ch="${C_G}yes${NC}" || ch="${C_Y}no${NC}"
  if   [[ "$chain" -le 2 && "$chain" -ge 1 ]]; then cc="${C_G}${chain}${NC}"
  elif [[ "$chain" -eq 3 ]]; then cc="${C_Y}${chain}${NC}"
  else cc="${C_R}${chain}${NC}"; fi

  printf "%-24s ${C_C}%10s${NC}  %-15b %-13b %-14s %-13b %-5s %b\n" \
    "$host" "$ac_disp" "$ct" "$ch" "${tempkey:0:14}" "$cc" "$code" "$qualify"

  if [[ "$mark" == "bad" ]]; then
    RESULTS+=("$host|999|no")
  else
    RESULTS+=("$host|$ac|$result_tag")
  fi
}

run_batch() {
  local hosts=("$@")
  print_header
  for h in "${hosts[@]}"; do
    h=$(normalize_host "$h"); [[ -z "$h" ]] && continue
    render_row "$h"
  done
}

# 按分类分组跑：每类一个小标题，最后统一排名
run_categories() {
  local cats=("$@") k host
  for k in "${cats[@]}"; do
    local list; list=$(cat_hosts "$k")
    [[ -z "$list" ]] && { printf "${C_R}未知分类: %s${NC}\n" "$k"; continue; }
    printf "\n${C_B}▎%s  ${C_D}[%s]${NC}\n" "$(cat_label "$k")" "$k"
    print_header
    while IFS= read -r host; do
      host=$(normalize_host "$host"); [[ -z "$host" ]] && continue
      render_row "$host"
    done <<< "$list"
  done
}

# 排序输出最佳推荐
print_best() {
  echo
  printf "${C_B}══ 本机最优 SNI 排名 (全合规优先，组内按握手升序) ══${NC}\n"
  local sorted top1="" top_tag=""
  sorted=$(printf '%s\n' "${RESULTS[@]}" \
    | awk -F'|' '$2!=999 {
        p=3
        if ($3=="full") p=0
        else if ($3=="chain") p=1
        else if ($3=="partial") p=2
        printf "%d|%s\n", p, $0
      }' \
    | sort -t'|' -k1,1n -k3,3n \
    | cut -d'|' -f2-)
  if [[ -z "$sorted" ]]; then
    printf "${C_R}没有站点满足证书有效且通过 TLS1.3，检查落地机出网/换候选列表${NC}\n"; return
  fi
  local rank=1
  while IFS='|' read -r host ac tag; do
    local badge=""
    case "$tag" in
      full)    badge="${C_G}[全合规]${NC}" ;;
      chain)   badge="${C_Y}[链偏长]${NC}" ;;
      partial) badge="${C_Y}[缺h2/x25519]${NC}" ;;
      *)       badge="${C_Y}[可用]${NC}" ;;
    esac
    printf "  %d) ${C_B}%-24s${NC} %ss  %b\n" "$rank" "$host" "$(awk "BEGIN{printf \"%.3f\",$ac}")" "$badge"
    if [[ $rank -eq 1 ]]; then
      top1="$host"
      top_tag="$tag"
    fi
    ((rank++)); [[ $rank -gt 6 ]] && break
  done <<< "$sorted"
  if [[ -n "$top1" && "$top_tag" == "full" ]]; then
    printf "\n${C_G}${C_B}→ 建议 dest/SNI: %s${NC}\n" "$top1"
  elif [[ -n "$top1" ]]; then
    printf "\n${C_Y}${C_B}→ 无全合规候选，备选 dest/SNI: %s${NC}\n" "$top1"
  fi
}

# 交互输入模式：一行可输入多个，逗号或空格分隔
interactive_loop() {
  echo
  printf "${C_B}── 自定义检测：输入网址/域名(可多个，逗号或空格分隔)；空行结束 ──${NC}\n"
  local raw tok
  while true; do
    printf "${C_C}检测 > ${NC}"; read -r raw || break
    [[ -z "$raw" ]] && break
    # 逗号统一成空格，再按空白切成多个
    raw="${raw//,/ }"
    local hosts=()
    for tok in $raw; do
      tok=$(normalize_host "$tok"); [[ -n "$tok" ]] && hosts+=("$tok")
    done
    [[ ${#hosts[@]} -eq 0 ]] && continue
    RESULTS=()                      # 本轮独立排名
    print_header
    for tok in "${hosts[@]}"; do render_row "$tok"; done
    [[ ${#hosts[@]} -gt 1 ]] && print_best   # 输入多个时给本轮排名+推荐
  done
}

# ============================  交互菜单  ======================================
# 从分类里多选 (数字，空格/逗号分隔; a=全部; 回车返回)
menu_pick_categories() {
  echo
  printf "${C_B}选择分类 (数字，空格或逗号分隔; a=全部; 回车返回):${NC}\n"
  local i=1 k
  for k in "${CAT_KEYS[@]}"; do
    printf "  ${C_C}%2d${NC}) %-7s %s ${C_D}(%d 站)${NC}\n" \
      "$i" "$k" "$(cat_label "$k")" "$(cat_hosts "$k" | grep -c .)"
    ((i++))
  done
  printf "${C_C}选择 > ${NC}"; local sel; read -r sel
  [[ -z "$sel" ]] && return 1
  if [[ "$sel" == "a" || "$sel" == "A" ]]; then SEL_CATS=("${CAT_KEYS[@]}"); return 0; fi
  sel="${sel//,/ }"; SEL_CATS=(); local n
  for n in $sel; do
    [[ "$n" =~ ^[0-9]+$ ]] || continue
    [[ "$n" -ge 1 && "$n" -le ${#CAT_KEYS[@]} ]] && SEL_CATS+=("${CAT_KEYS[$((n-1))]}")
  done
  [[ ${#SEL_CATS[@]} -eq 0 ]] && return 1
  return 0
}

# 设置探测次数/超时
settings_menu() {
  echo
  printf "${C_B}当前设置: 每站探测 %d 次 · 单次超时 %d 秒${NC}\n" "$ROUNDS" "$TIMEOUT"
  printf "新的探测次数 (回车不改): "; local r; read -r r
  [[ "$r" =~ ^[0-9]+$ && "$r" -ge 1 ]] && ROUNDS="$r"
  printf "新的超时秒数 (回车不改): "; local t; read -r t
  [[ "$t" =~ ^[0-9]+$ && "$t" -ge 1 ]] && TIMEOUT="$t"
  printf "${C_G}已更新: %d 次 · %d 秒${NC}\n" "$ROUNDS" "$TIMEOUT"
}

# 跑选定分类并出排名
run_selected() {
  RESULTS=()
  run_categories "$@"
  print_best
}

# 从地区里选一个 (数字; 回车返回)
menu_pick_region() {
  echo
  printf "${C_B}选择落地机所在/目标地区 (数字; 回车返回):${NC}\n"
  printf "${C_D}  会测「该地区归属站 + 全球通用站」，推荐里挑就近又合规的。${NC}\n"
  local i=1 r
  for r in "${REGION_KEYS[@]}"; do
    local n; n=$(region_hosts "$r" | grep -c .)
    printf "  ${C_C}%2d${NC}) %-7s %s ${C_D}(%d 站)${NC}\n" "$i" "$r" "$(region_label "$r")" "$n"
    ((i++))
  done
  printf "${C_C}选择 > ${NC}"; local sel; read -r sel
  [[ -z "$sel" ]] && return 1
  [[ "$sel" =~ ^[0-9]+$ ]] || return 1
  [[ "$sel" -ge 1 && "$sel" -le ${#REGION_KEYS[@]} ]] || return 1
  SEL_REGION="${REGION_KEYS[$((sel-1))]}"
  return 0
}

# 按地区跑：该区归属站 + 全球站，出排名
run_region() {
  local r="$1" rh=() h
  region_exists "$r" || { printf "${C_R}未知地区: %s${NC}\n" "$r"; return 1; }
  while IFS= read -r h; do [[ -n "$h" ]] && rh+=("$h"); done < <(region_hosts "$r")
  [[ ${#rh[@]} -eq 0 ]] && { printf "${C_R}未知地区: %s${NC}\n" "$r"; return 1; }
  RESULTS=()
  printf "\n${C_B}▎地区推荐: %s ${C_D}[%s] · 含全球通用站${NC}\n" "$(region_label "$r")" "$r"
  print_header
  for h in "${rh[@]}"; do render_row "$h"; done
  print_best
}

# 清屏 (仅终端下生效，管道/重定向不清，避免破坏日志)
cls() {
  [[ -t 1 ]] || return 0
  if command -v clear >/dev/null 2>&1; then clear; else printf '\033[2J\033[H'; fi
}

# 看完结果后暂停，回车返回主菜单
pause_return() {
  printf "\n${C_D}按回车返回主菜单...${NC}"; read -r _ || true
}

# 主菜单
main_menu() {
  local TOTAL_SITES; TOTAL_SITES=$(for k in "${CAT_KEYS[@]}"; do cat_hosts "$k"; done | grep -c .)
  while true; do
    cls                                   # 返回/进入主菜单都清屏
    printf "${C_B}════════ Reality SNI 检测 · 主菜单 ════════${NC}\n"
    printf "${C_D}仅用于连通性/TLS 握手检测，请合规使用，后果自负${NC}\n\n"
    printf "  ${C_C}1${NC}) 快速测试   ${C_D}(cdn + cloud + tech，最常用)${NC}\n"
    printf "  ${C_C}2${NC}) 全部分类   ${C_D}(%d 站，较慢)${NC}\n" "$TOTAL_SITES"
    printf "  ${C_C}3${NC}) 选择分类测试\n"
    printf "  ${C_C}4${NC}) 按地区推荐   ${C_D}(就近 + 合规)${NC}\n"
    printf "  ${C_C}5${NC}) 自定义网址检测   ${C_D}(一行可多站)${NC}\n"
    printf "  ${C_C}6${NC}) 设置   ${C_D}(次数=%d 超时=%ds)${NC}\n" "$ROUNDS" "$TIMEOUT"
    printf "  ${C_C}0${NC}) 退出\n"
    printf "${C_C}请选择 > ${NC}"; local c; read -r c || break
    case "$c" in
      1) cls; run_selected cdn cloud tech;        pause_return ;;
      2) cls; run_selected "${CAT_KEYS[@]}";       pause_return ;;
      3) cls; if menu_pick_categories; then run_selected "${SEL_CATS[@]}"; pause_return; fi ;;
      4) cls; if menu_pick_region; then run_region "$SEL_REGION"; pause_return; fi ;;
      5) cls; interactive_loop;                    pause_return ;;
      6) cls; settings_menu;                       pause_return ;;
      0|q|Q) cls; printf "${C_D}再见。${NC}\n"; break ;;
      "") : ;;                                     # 空输入：循环顶部重绘
      *) printf "${C_R}无效选择: %s${NC}\n" "$c"; sleep 1 ;;
    esac
  done
}

# ==============================  主流程  ======================================
printf "${C_B}Reality SNI 候选检测${NC}  ${C_D}(每站%d次取最小 · 超时%ds)${NC}\n" "$ROUNDS" "$TIMEOUT"
printf "${C_D}仅用于连通性/TLS 握手检测，请在符合当地法律法规与服务条款前提下使用，后果自负。${NC}\n"

# -i 只进交互输入
if [[ "$INTERACTIVE_ONLY" -eq 1 ]]; then
  interactive_loop; exit 0
fi

# -r 按地区直接跑
if [[ -n "$SEL_REGION" ]]; then
  run_region "$SEL_REGION"
  exit $?
fi

# 传了 CLI 参数(分类/追加/SNI_HOSTS 覆盖) → 直接跑，不进菜单
if [[ ${#SNI_OVERRIDE[@]} -gt 0 || ${#SEL_CATS[@]} -gt 0 || ${#EXTRA_HOSTS[@]} -gt 0 ]]; then
  RESULTS=()
  if [[ ${#SNI_OVERRIDE[@]} -gt 0 ]]; then
    run_batch "${SNI_OVERRIDE[@]}"
  else
    [[ ${#SEL_CATS[@]} -eq 0 ]] && SEL_CATS=("${CAT_KEYS[@]}")
    run_categories "${SEL_CATS[@]}"
    if [[ ${#EXTRA_HOSTS[@]} -gt 0 ]]; then
      printf "\n${C_B}▎追加站点  ${C_D}[-a]${NC}\n"
      run_batch "${EXTRA_HOSTS[@]}"
    fi
  fi
  print_best
  if [[ -t 0 ]]; then
    echo; printf "${C_D}(可继续输入网址补测，直接回车退出)${NC}\n"
    interactive_loop
  fi
  printf "${C_D}完成。${NC}\n"
  exit 0
fi

# 无参数 → 进菜单
main_menu
